// GENERATED by scripts/gen_limits.py from limits.json (repository root).
// Do not edit by hand: run `make limits`. Values come from AWS_API_NOTES.md
// §2, §3, §6, §11. Nothing here is user-configurable: these are API facts.

export const MAX_DURATION_SECONDS = 28800 as const;
export const MIN_DURATION_SECONDS = 1 as const;
export const IDLE_MAX_IDLE_MIN_SECONDS = 60 as const;
export const IDLE_SUSPENDED_MIN_SECONDS = 0 as const;

export const TOKEN_TTL_MINUTES = 60 as const;
export const TOKEN_TTL_MIN_MINUTES = 1 as const;
export const TOKEN_REFRESH_AFTER_MINUTES = 45 as const;
export const TOKEN_REFRESH_RETRY_SECONDS = 60 as const;

export const RUN_HOOK_PAYLOAD_MAX_CHARS = 4096 as const;
export const CLIENT_TOKEN_MAX = 128 as const;
export const MICROVM_ID_MIN_LENGTH = 1 as const;
export const MICROVM_ID_MAX_LENGTH = 256 as const;
export const LIST_MAX_RESULTS = 50 as const;
export const NETWORK_CONNECTORS_MAX = 10 as const;

export const DEFAULT_PORT = 8080 as const;
export const HOOKS_PORT = 9000 as const;
export const PORT_MIN = 1 as const;
export const PORT_MAX = 65535 as const;
export const ENDPOINT_TLS_PORT = 443 as const;
export const HOOK_PATH_PREFIX = "/aws/lambda-microvms/runtime/v1" as const;

export const MAX_CONCURRENT_CONNECTIONS_1_VCPU = 8 as const;

export const MICROVM_STATES = [
  "PENDING",
  "RUNNING",
  "SUSPENDING",
  "SUSPENDED",
  "TERMINATING",
  "TERMINATED",
] as const;
export const TERMINAL_STATES: ReadonlySet<string> = new Set(["TERMINATING", "TERMINATED"]);
export const SUSPENDED_STATES: ReadonlySet<string> = new Set(["SUSPENDING", "SUSPENDED"]);

export const MANAGED_NETWORK_CONNECTORS: ReadonlySet<string> = new Set([
  "ALL_INGRESS",
  "NO_INGRESS",
  "SHELL_INGRESS",
  "INTERNET_EGRESS",
]);

export const SUPPORTED_REGIONS = [
  "us-east-1",
  "us-east-2",
  "us-west-2",
  "eu-west-1",
  "ap-northeast-1",
  "ap-south-1",
  "ap-southeast-1",
  "ap-southeast-2",
  "eu-central-1",
  "eu-north-1",
] as const;

export const API_TPS: Readonly<Record<string, number>> = {
  CreateMicrovmAuthToken: 50,
  CreateMicrovmShellAuthToken: 5,
  GetMicrovm: 100,
  ResumeMicrovm: 5,
  RunMicrovm: 5,
  SuspendMicrovm: 2,
  TerminateMicrovm: 10,
};

export const PERSIST_KEY_PREFIX_MAX_BYTES = 900 as const;
export const PERSIST_EXCLUDE_MAX = 64 as const;
export const S3_BUCKET_NAME_MIN = 3 as const;
export const S3_BUCKET_NAME_MAX = 63 as const;
export const DEFAULT_PERSIST_TIMEOUT_SECONDS = 600 as const;

export const EGRESS_MAX_ENTRIES_PER_LIST = 256 as const;
export const EGRESS_MAX_HOSTNAME_ENTRIES = 64 as const;
export const EGRESS_HOSTNAME_MAX_CHARS = 253 as const;
export const EGRESS_PROXY_CREDENTIAL_MAX_BYTES = 255 as const;

export const LIFECYCLE_CAP_MARGIN_SECONDS = 60 as const;
export const LIFECYCLE_MIN_MAX_LIFETIME_SECONDS = 120 as const;
export const LIFECYCLE_RESUME_GRACE_SECONDS = 30 as const;
export const LIFECYCLE_AUTO_RESUME_MIN_SECONDS = 300 as const;
export const LIFECYCLE_MIN_TIMEOUT_SECONDS = 1 as const;
export const LIFECYCLE_TIMEOUT_EXIT_CODE = 124 as const;

export const TRANSFER_DEFAULT_PREFIX = "rayito-transfer" as const;
export const TRANSFER_DEFAULT_EXPIRES_IN_SECONDS = 3600 as const;
export const TRANSFER_DEFAULT_MAX_EXPIRES_IN_SECONDS = 86400 as const;
export const TRANSFER_PRESIGN_MAX_SECONDS = 604800 as const;
export const TRANSFER_DEFAULT_THRESHOLD_BYTES = 8388608 as const;
export const TRANSFER_THRESHOLD_MIN_BYTES = 1048576 as const;
export const TRANSFER_DEFAULT_MULTIPART_THRESHOLD_BYTES = 5368709120 as const;
export const TRANSFER_MULTIPART_THRESHOLD_MIN_BYTES = 16777216 as const;
export const TRANSFER_SINGLE_PUT_MAX_BYTES = 5368709120 as const;
export const TRANSFER_PART_SIZE_MIN_BYTES = 8388608 as const;
export const TRANSFER_MAX_PARTS = 1000 as const;

export const TRANSFER_MAX_ACTIVE = 16 as const;
export const TRANSFER_MAX_RUNNING = 2 as const;
export const TRANSFER_RETAINED_MAX = 64 as const;
export const TRANSFER_RETAINED_SECONDS = 1800 as const;
export const TRANSFER_PROBE_BUDGET_MS = 2000 as const;
export const TRANSFER_POLL_FAST_INTERVAL_MS = 1000 as const;
export const TRANSFER_POLL_SLOW_INTERVAL_MS = 5000 as const;
export const TRANSFER_POLL_FAST_WINDOW_SECONDS = 600 as const;
export const TRANSFER_URL_MAX_BYTES = 8192 as const;
export const TRANSFER_INTERNAL_EXPIRES_IN_SECONDS = 900 as const;
export const TRANSFER_CONNECT_TIMEOUT_MS = 5000 as const;
export const TRANSFER_IDLE_TIMEOUT_MS = 30000 as const;

export const METADATA_MAX_BYTES = 4000 as const;
export const METADATA_MAX_KEYS = 64 as const;
export const METADATA_XATTR_PREFIX = "user.rayito." as const;
export const COMPRESSION_OPT_IN_HEADER = "rayito-compress" as const;
