# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import code_pb2 as rayito_dot_v1_dot_code__pb2


class CodeServiceStub:
    """Ejecución de código con estado persistente y resultados enriquecidos.
    Implementado por el agente como proxy al kernel-sidecar (un kernel Jupyter
    por contexto).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateContext = channel.unary_unary(
                '/rayito.v1.CodeService/CreateContext',
                request_serializer=rayito_dot_v1_dot_code__pb2.CreateContextRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_code__pb2.CreateContextResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/rayito.v1.CodeService/Execute',
                request_serializer=rayito_dot_v1_dot_code__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_code__pb2.ExecuteEvent.FromString,
                _registered_method=True)
        self.Reattach = channel.unary_stream(
                '/rayito.v1.CodeService/Reattach',
                request_serializer=rayito_dot_v1_dot_code__pb2.ReattachRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_code__pb2.ExecuteEvent.FromString,
                _registered_method=True)
        self.ListContexts = channel.unary_unary(
                '/rayito.v1.CodeService/ListContexts',
                request_serializer=rayito_dot_v1_dot_code__pb2.ListContextsRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_code__pb2.ListContextsResponse.FromString,
                _registered_method=True)
        self.DestroyContext = channel.unary_unary(
                '/rayito.v1.CodeService/DestroyContext',
                request_serializer=rayito_dot_v1_dot_code__pb2.DestroyContextRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_code__pb2.DestroyContextResponse.FromString,
                _registered_method=True)
        self.RestartContext = channel.unary_unary(
                '/rayito.v1.CodeService/RestartContext',
                request_serializer=rayito_dot_v1_dot_code__pb2.RestartContextRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_code__pb2.RestartContextResponse.FromString,
                _registered_method=True)


class CodeServiceServicer:
    """Ejecución de código con estado persistente y resultados enriquecidos.
    Implementado por el agente como proxy al kernel-sidecar (un kernel Jupyter
    por contexto).
    """

    def CreateContext(self, request, context):
        """Crea un contexto de ejecución (un kernel con su propio scope y cwd).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Ejecuta código y transmite la salida a medida que se produce. Si el cliente
        cancela el stream, el agente interrumpe la ejecución en el kernel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reattach(self, request, context):
        """Se reengancha a una ejecución en curso tras perder el stream (p. ej. tras
        suspend/resume). UNIMPLEMENTED hasta M5.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContexts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartContext(self, request, context):
        """Reinicia el kernel de un contexto perdiendo su estado. Útil tras un
        proceso que deja el intérprete inservible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateContext': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContext,
                    request_deserializer=rayito_dot_v1_dot_code__pb2.CreateContextRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_code__pb2.CreateContextResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=rayito_dot_v1_dot_code__pb2.ExecuteRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_code__pb2.ExecuteEvent.SerializeToString,
            ),
            'Reattach': grpc.unary_stream_rpc_method_handler(
                    servicer.Reattach,
                    request_deserializer=rayito_dot_v1_dot_code__pb2.ReattachRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_code__pb2.ExecuteEvent.SerializeToString,
            ),
            'ListContexts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContexts,
                    request_deserializer=rayito_dot_v1_dot_code__pb2.ListContextsRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_code__pb2.ListContextsResponse.SerializeToString,
            ),
            'DestroyContext': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyContext,
                    request_deserializer=rayito_dot_v1_dot_code__pb2.DestroyContextRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_code__pb2.DestroyContextResponse.SerializeToString,
            ),
            'RestartContext': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartContext,
                    request_deserializer=rayito_dot_v1_dot_code__pb2.RestartContextRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_code__pb2.RestartContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.CodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.CodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeService:
    """Ejecución de código con estado persistente y resultados enriquecidos.
    Implementado por el agente como proxy al kernel-sidecar (un kernel Jupyter
    por contexto).
    """

    @staticmethod
    def CreateContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.CodeService/CreateContext',
            rayito_dot_v1_dot_code__pb2.CreateContextRequest.SerializeToString,
            rayito_dot_v1_dot_code__pb2.CreateContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.CodeService/Execute',
            rayito_dot_v1_dot_code__pb2.ExecuteRequest.SerializeToString,
            rayito_dot_v1_dot_code__pb2.ExecuteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reattach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.CodeService/Reattach',
            rayito_dot_v1_dot_code__pb2.ReattachRequest.SerializeToString,
            rayito_dot_v1_dot_code__pb2.ExecuteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContexts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.CodeService/ListContexts',
            rayito_dot_v1_dot_code__pb2.ListContextsRequest.SerializeToString,
            rayito_dot_v1_dot_code__pb2.ListContextsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.CodeService/DestroyContext',
            rayito_dot_v1_dot_code__pb2.DestroyContextRequest.SerializeToString,
            rayito_dot_v1_dot_code__pb2.DestroyContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.CodeService/RestartContext',
            rayito_dot_v1_dot_code__pb2.RestartContextRequest.SerializeToString,
            rayito_dot_v1_dot_code__pb2.RestartContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
