# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import configure_pb2 as rayito_dot_v1_dot_configure__pb2


class ConfigureServiceStub:
    """M15 (Rayito 0.6, foundations): el único canal de configuración por
    sandbox tras `/run`. Exige x-access-token como cualquier RPC salvo
    Health. Sólo se llama cuando al menos una sección de 0.6 está activada
    explícitamente por el SDK (ADR-014 regla 4: ninguna variable de entorno
    activa una función de coste); sin eso, el SDK no hace ninguna llamada a
    este servicio y el comportamiento es byte a byte el de 0.5.x.

    Semántica de `ConfigureRequest`: una sección ausente se deja tal cual; una
    presente (incluso vacía) sustituye el estado anterior de esa función.
    Orden de aplicación fijo (`rayd_core::configure::APPLY_ORDER`): events →
    telemetry → gateway → s3_mounts → efs_volumes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/rayito.v1.ConfigureService/Configure',
                request_serializer=rayito_dot_v1_dot_configure__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_configure__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.ConfigureStatus = channel.unary_unary(
                '/rayito.v1.ConfigureService/ConfigureStatus',
                request_serializer=rayito_dot_v1_dot_configure__pb2.ConfigureStatusRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_configure__pb2.ConfigureStatusResponse.FromString,
                _registered_method=True)


class ConfigureServiceServicer:
    """M15 (Rayito 0.6, foundations): el único canal de configuración por
    sandbox tras `/run`. Exige x-access-token como cualquier RPC salvo
    Health. Sólo se llama cuando al menos una sección de 0.6 está activada
    explícitamente por el SDK (ADR-014 regla 4: ninguna variable de entorno
    activa una función de coste); sin eso, el SDK no hace ninguna llamada a
    este servicio y el comportamiento es byte a byte el de 0.5.x.

    Semántica de `ConfigureRequest`: una sección ausente se deja tal cual; una
    presente (incluso vacía) sustituye el estado anterior de esa función.
    Orden de aplicación fijo (`rayd_core::configure::APPLY_ORDER`): events →
    telemetry → gateway → s3_mounts → efs_volumes.
    """

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=rayito_dot_v1_dot_configure__pb2.ConfigureRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_configure__pb2.ConfigureResponse.SerializeToString,
            ),
            'ConfigureStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureStatus,
                    request_deserializer=rayito_dot_v1_dot_configure__pb2.ConfigureStatusRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_configure__pb2.ConfigureStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.ConfigureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.ConfigureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigureService:
    """M15 (Rayito 0.6, foundations): el único canal de configuración por
    sandbox tras `/run`. Exige x-access-token como cualquier RPC salvo
    Health. Sólo se llama cuando al menos una sección de 0.6 está activada
    explícitamente por el SDK (ADR-014 regla 4: ninguna variable de entorno
    activa una función de coste); sin eso, el SDK no hace ninguna llamada a
    este servicio y el comportamiento es byte a byte el de 0.5.x.

    Semántica de `ConfigureRequest`: una sección ausente se deja tal cual; una
    presente (incluso vacía) sustituye el estado anterior de esa función.
    Orden de aplicación fijo (`rayd_core::configure::APPLY_ORDER`): events →
    telemetry → gateway → s3_mounts → efs_volumes.
    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.ConfigureService/Configure',
            rayito_dot_v1_dot_configure__pb2.ConfigureRequest.SerializeToString,
            rayito_dot_v1_dot_configure__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.ConfigureService/ConfigureStatus',
            rayito_dot_v1_dot_configure__pb2.ConfigureStatusRequest.SerializeToString,
            rayito_dot_v1_dot_configure__pb2.ConfigureStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
