# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rayito/v1/features.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'rayito/v1/features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18rayito/v1/features.proto\x12\trayito.v1\"\xcc\x02\n\rAgentFeatures\x12\x1c\n\tconfigure\x18\x01 \x01(\x08R\tconfigure\x12\x1b\n\ts3_mounts\x18\x02 \x01(\x08R\x08s3Mounts\x12\x1f\n\x0b\x65\x66s_volumes\x18\x03 \x01(\x08R\nefsVolumes\x12)\n\x10lifecycle_events\x18\x04 \x01(\x08R\x0flifecycleEvents\x12)\n\x10telemetry_export\x18\x05 \x01(\x08R\x0ftelemetryExport\x12%\n\x0esecret_gateway\x18\x06 \x01(\x08R\rsecretGateway\x12%\n\x0etemplate_start\x18\x07 \x01(\x08R\rtemplateStart\x12;\n\x0broot_egress\x18\x08 \x03(\x0e\x32\x1a.rayito.v1.RootEgressClassR\nrootEgress*\xbf\x01\n\x0fRootEgressClass\x12!\n\x1dROOT_EGRESS_CLASS_UNSPECIFIED\x10\x00\x12\x18\n\x14ROOT_EGRESS_CLASS_S3\x10\x01\x12%\n!ROOT_EGRESS_CLASS_CLOUDWATCH_OTLP\x10\x02\x12-\n)ROOT_EGRESS_CLASS_SECRET_GATEWAY_UPSTREAM\x10\x03\x12\x19\n\x15ROOT_EGRESS_CLASS_EFS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rayito.v1.features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOTEGRESSCLASS']._serialized_start=375
  _globals['_ROOTEGRESSCLASS']._serialized_end=566
  _globals['_AGENTFEATURES']._serialized_start=40
  _globals['_AGENTFEATURES']._serialized_end=372
# @@protoc_insertion_point(module_scope)
