# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import filesystem_pb2 as rayito_dot_v1_dot_filesystem__pb2


class FilesystemServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_stream(
                '/rayito.v1.FilesystemService/Read',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.ReadRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.stream_unary(
                '/rayito.v1.FilesystemService/Write',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.WriteRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/rayito.v1.FilesystemService/Stat',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.StatRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.StatResponse.FromString,
                _registered_method=True)
        self.ListDir = channel.unary_unary(
                '/rayito.v1.FilesystemService/ListDir',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.ListDirRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.ListDirResponse.FromString,
                _registered_method=True)
        self.MakeDir = channel.unary_unary(
                '/rayito.v1.FilesystemService/MakeDir',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.MakeDirRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.MakeDirResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/rayito.v1.FilesystemService/Move',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.MoveRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/rayito.v1.FilesystemService/Remove',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.RemoveRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.RemoveResponse.FromString,
                _registered_method=True)
        self.WatchDir = channel.unary_stream(
                '/rayito.v1.FilesystemService/WatchDir',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.WatchDirRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.WatchDirResponse.FromString,
                _registered_method=True)
        self.Checkpoint = channel.unary_stream(
                '/rayito.v1.FilesystemService/Checkpoint',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.CheckpointEvent.FromString,
                _registered_method=True)
        self.Restore = channel.unary_stream(
                '/rayito.v1.FilesystemService/Restore',
                request_serializer=rayito_dot_v1_dot_filesystem__pb2.RestoreRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_filesystem__pb2.RestoreEvent.FromString,
                _registered_method=True)


class FilesystemServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Lectura en streaming en chunks de 256 KiB.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request_iterator, context):
        """Escritura en streaming. Un WriteRequest con `path` empieza un fichero nuevo
        (cerrando el anterior), así que N ficheros pueden compartir un stream.
        Chunks <= 1 MiB; un mensaje > 4 MiB se rechaza con INVALID_ARGUMENT.
        El agente escribe en un temporal del mismo directorio, fsync y rename
        (atómico), creando padres y asignando propietario al usuario indicado.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """NOT_FOUND si no existe (el SDK lo traduce en exists() == false).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeDir(self, request, context):
        """ALREADY_EXISTS si el directorio ya existe (SDK: make_dir() == false);
        INVALID_ARGUMENT si existe algo que no es un directorio.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchDir(self, request, context):
        """Observa un directorio. El primer mensaje es WatchStarted, emitido sólo
        cuando el watch inotify está instalado; NOT_FOUND / INVALID_ARGUMENT llegan
        como status gRPC antes de cualquier mensaje. Sin debounce.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoint(self, request, context):
        """Empaqueta el HOME del usuario (tar.gz, lista de exclusión documentada)
        y lo sube a S3 con las credenciales del execution role, como root.
        Un solo checkpoint o restore a la vez por sandbox (FAILED_PRECONDITION).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Descarga <key_prefix>/manifest.json y <key_prefix>/home.tar.gz y los
        extrae en el HOME del usuario (sin seguir ni escapar del HOME).
        NOT_FOUND si no hay manifest bajo el prefijo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.ReadRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.stream_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.WriteRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.WriteResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.StatRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.StatResponse.SerializeToString,
            ),
            'ListDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDir,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.ListDirRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.ListDirResponse.SerializeToString,
            ),
            'MakeDir': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDir,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.MakeDirRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.MakeDirResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.MoveRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.MoveResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.RemoveRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.RemoveResponse.SerializeToString,
            ),
            'WatchDir': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchDir,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.WatchDirRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.WatchDirResponse.SerializeToString,
            ),
            'Checkpoint': grpc.unary_stream_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.CheckpointRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.CheckpointEvent.SerializeToString,
            ),
            'Restore': grpc.unary_stream_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=rayito_dot_v1_dot_filesystem__pb2.RestoreRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_filesystem__pb2.RestoreEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.FilesystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.FilesystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilesystemService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.FilesystemService/Read',
            rayito_dot_v1_dot_filesystem__pb2.ReadRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/rayito.v1.FilesystemService/Write',
            rayito_dot_v1_dot_filesystem__pb2.WriteRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.FilesystemService/Stat',
            rayito_dot_v1_dot_filesystem__pb2.StatRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.FilesystemService/ListDir',
            rayito_dot_v1_dot_filesystem__pb2.ListDirRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.ListDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.FilesystemService/MakeDir',
            rayito_dot_v1_dot_filesystem__pb2.MakeDirRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.MakeDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.FilesystemService/Move',
            rayito_dot_v1_dot_filesystem__pb2.MoveRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.FilesystemService/Remove',
            rayito_dot_v1_dot_filesystem__pb2.RemoveRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.RemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.FilesystemService/WatchDir',
            rayito_dot_v1_dot_filesystem__pb2.WatchDirRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.WatchDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.FilesystemService/Checkpoint',
            rayito_dot_v1_dot_filesystem__pb2.CheckpointRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.CheckpointEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.FilesystemService/Restore',
            rayito_dot_v1_dot_filesystem__pb2.RestoreRequest.SerializeToString,
            rayito_dot_v1_dot_filesystem__pb2.RestoreEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
