# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import health_pb2 as rayito_dot_v1_dot_health__pb2


class HealthServiceStub:
    """Estado del agente y del sandbox. Health es el único RPC que no exige
    `x-access-token`: es la sonda de readiness y liveness del SDK (el estado de
    `get-microvm` es eventualmente consistente y no sirve para eso).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/rayito.v1.HealthService/Health',
                request_serializer=rayito_dot_v1_dot_health__pb2.HealthRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_health__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/rayito.v1.HealthService/Metrics',
                request_serializer=rayito_dot_v1_dot_health__pb2.MetricsRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_health__pb2.MetricsResponse.FromString,
                _registered_method=True)


class HealthServiceServicer:
    """Estado del agente y del sandbox. Health es el único RPC que no exige
    `x-access-token`: es la sonda de readiness y liveness del SDK (el estado de
    `get-microvm` es eventualmente consistente y no sirve para eso).
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rayito_dot_v1_dot_health__pb2.HealthRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_health__pb2.HealthResponse.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=rayito_dot_v1_dot_health__pb2.MetricsRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_health__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService:
    """Estado del agente y del sandbox. Health es el único RPC que no exige
    `x-access-token`: es la sonda de readiness y liveness del SDK (el estado de
    `get-microvm` es eventualmente consistente y no sirve para eso).
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.HealthService/Health',
            rayito_dot_v1_dot_health__pb2.HealthRequest.SerializeToString,
            rayito_dot_v1_dot_health__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.HealthService/Metrics',
            rayito_dot_v1_dot_health__pb2.MetricsRequest.SerializeToString,
            rayito_dot_v1_dot_health__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
