# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rayito/v1/lifecycle_events.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'rayito/v1/lifecycle_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n rayito/v1/lifecycle_events.proto\x12\trayito.v1\"\x17\n\x15LifecycleEventsConfig\"\x17\n\x15LifecycleEventsStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rayito.v1.lifecycle_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIFECYCLEEVENTSCONFIG']._serialized_start=47
  _globals['_LIFECYCLEEVENTSCONFIG']._serialized_end=70
  _globals['_LIFECYCLEEVENTSSTATUS']._serialized_start=72
  _globals['_LIFECYCLEEVENTSSTATUS']._serialized_end=95
# @@protoc_insertion_point(module_scope)
