# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import lifecycle_pb2 as rayito_dot_v1_dot_lifecycle__pb2


class LifecycleServiceStub:
    """Plazo lógico del sandbox impuesto por rayd (ADR-011). SetTimeout exige
    x-access-token: el código del sandbox no puede alargarse a sí mismo.
    Más allá del tope (cap) responde INVALID_ARGUMENT con
    "timeout beyond cap; cap_unix_ms=<n>"; sobre un sandbox sin bloque
    lifecycle en el runHookPayload, FAILED_PRECONDITION "lifecycle_unmanaged".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetTimeout = channel.unary_unary(
                '/rayito.v1.LifecycleService/SetTimeout',
                request_serializer=rayito_dot_v1_dot_lifecycle__pb2.SetTimeoutRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_lifecycle__pb2.LifecycleState.FromString,
                _registered_method=True)


class LifecycleServiceServicer:
    """Plazo lógico del sandbox impuesto por rayd (ADR-011). SetTimeout exige
    x-access-token: el código del sandbox no puede alargarse a sí mismo.
    Más allá del tope (cap) responde INVALID_ARGUMENT con
    "timeout beyond cap; cap_unix_ms=<n>"; sobre un sandbox sin bloque
    lifecycle en el runHookPayload, FAILED_PRECONDITION "lifecycle_unmanaged".
    """

    def SetTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LifecycleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeout,
                    request_deserializer=rayito_dot_v1_dot_lifecycle__pb2.SetTimeoutRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_lifecycle__pb2.LifecycleState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.LifecycleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.LifecycleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LifecycleService:
    """Plazo lógico del sandbox impuesto por rayd (ADR-011). SetTimeout exige
    x-access-token: el código del sandbox no puede alargarse a sí mismo.
    Más allá del tope (cap) responde INVALID_ARGUMENT con
    "timeout beyond cap; cap_unix_ms=<n>"; sobre un sandbox sin bloque
    lifecycle en el runHookPayload, FAILED_PRECONDITION "lifecycle_unmanaged".
    """

    @staticmethod
    def SetTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.LifecycleService/SetTimeout',
            rayito_dot_v1_dot_lifecycle__pb2.SetTimeoutRequest.SerializeToString,
            rayito_dot_v1_dot_lifecycle__pb2.LifecycleState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
