# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rayito/v1/lifecycle.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'rayito/v1/lifecycle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19rayito/v1/lifecycle.proto\x12\trayito.v1\"^\n\x11SetTimeoutRequest\x12\x1d\n\ntimeout_ms\x18\x01 \x01(\x04R\ttimeoutMs\x12*\n\x04mode\x18\x02 \x01(\x0e\x32\x16.rayito.v1.TimeoutModeR\x04mode\"\xa4\x02\n\x0eLifecycleState\x12/\n\x05phase\x18\x01 \x01(\x0e\x32\x19.rayito.v1.LifecyclePhaseR\x05phase\x12(\n\x10\x64\x65\x61\x64line_unix_ms\x18\x02 \x01(\x03R\x0e\x64\x65\x61\x64lineUnixMs\x12\x1e\n\x0b\x63\x61p_unix_ms\x18\x03 \x01(\x03R\tcapUnixMs\x12\x1d\n\ntimeout_ms\x18\x04 \x01(\x04R\ttimeoutMs\x12\x37\n\non_timeout\x18\x05 \x01(\x0e\x32\x18.rayito.v1.TimeoutActionR\tonTimeout\x12\x1f\n\x0b\x61uto_resume\x18\x06 \x01(\x08R\nautoResume\x12\x1e\n\nextensions\x18\x07 \x01(\rR\nextensions*^\n\x0bTimeoutMode\x12\x1c\n\x18TIMEOUT_MODE_UNSPECIFIED\x10\x00\x12\x16\n\x12TIMEOUT_MODE_EXACT\x10\x01\x12\x19\n\x15TIMEOUT_MODE_AT_LEAST\x10\x02*b\n\rTimeoutAction\x12\x1e\n\x1aTIMEOUT_ACTION_UNSPECIFIED\x10\x00\x12\x17\n\x13TIMEOUT_ACTION_KILL\x10\x01\x12\x18\n\x14TIMEOUT_ACTION_PAUSE\x10\x02*\xab\x01\n\x0eLifecyclePhase\x12\x1f\n\x1bLIFECYCLE_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n\x19LIFECYCLE_PHASE_UNMANAGED\x10\x01\x12\x1a\n\x16LIFECYCLE_PHASE_ACTIVE\x10\x02\x12 \n\x1cLIFECYCLE_PHASE_RESUME_GRACE\x10\x03\x12\x1b\n\x17LIFECYCLE_PHASE_EXPIRED\x10\x04\x32Y\n\x10LifecycleService\x12\x45\n\nSetTimeout\x12\x1c.rayito.v1.SetTimeoutRequest\x1a\x19.rayito.v1.LifecycleStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rayito.v1.lifecycle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEOUTMODE']._serialized_start=431
  _globals['_TIMEOUTMODE']._serialized_end=525
  _globals['_TIMEOUTACTION']._serialized_start=527
  _globals['_TIMEOUTACTION']._serialized_end=625
  _globals['_LIFECYCLEPHASE']._serialized_start=628
  _globals['_LIFECYCLEPHASE']._serialized_end=799
  _globals['_SETTIMEOUTREQUEST']._serialized_start=40
  _globals['_SETTIMEOUTREQUEST']._serialized_end=134
  _globals['_LIFECYCLESTATE']._serialized_start=137
  _globals['_LIFECYCLESTATE']._serialized_end=429
  _globals['_LIFECYCLESERVICE']._serialized_start=801
  _globals['_LIFECYCLESERVICE']._serialized_end=890
# @@protoc_insertion_point(module_scope)
