# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rayito/v1/network.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'rayito/v1/network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rayito/v1/network.proto\x12\trayito.v1\"\x83\x01\n\x0b\x45gressProxy\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x1f\n\x08username\x18\x02 \x01(\tH\x00R\x08username\x88\x01\x01\x12\x1f\n\x08password\x18\x03 \x01(\tH\x01R\x08password\x88\x01\x01\x42\x0b\n\t_usernameB\x0b\n\t_password\"\x98\x01\n\rNetworkPolicy\x12\x1b\n\tallow_out\x18\x01 \x03(\tR\x08\x61llowOut\x12\x19\n\x08\x64\x65ny_out\x18\x02 \x03(\tR\x07\x64\x65nyOut\x12>\n\x0c\x65gress_proxy\x18\x03 \x01(\x0b\x32\x16.rayito.v1.EgressProxyH\x00R\x0b\x65gressProxy\x88\x01\x01\x42\x0f\n\r_egress_proxy\"H\n\x14UpdateNetworkRequest\x12\x30\n\x06policy\x18\x01 \x01(\x0b\x32\x18.rayito.v1.NetworkPolicyR\x06policy\"\x13\n\x11GetNetworkRequest\"\xe8\x01\n\x0cNetworkState\x12\x1b\n\tallow_out\x18\x01 \x03(\tR\x08\x61llowOut\x12\x19\n\x08\x64\x65ny_out\x18\x02 \x03(\tR\x07\x64\x65nyOut\x12\x36\n\x17\x65gress_proxy_configured\x18\x03 \x01(\x08R\x15\x65gressProxyConfigured\x12>\n\x0b\x65nforcement\x18\x04 \x01(\x0e\x32\x1c.rayito.v1.EgressEnforcementR\x0b\x65nforcement\x12(\n\x10local_proxy_port\x18\x05 \x01(\rR\x0elocalProxyPort*\xa8\x01\n\x11\x45gressEnforcement\x12\"\n\x1e\x45GRESS_ENFORCEMENT_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45GRESS_ENFORCEMENT_NONE\x10\x01\x12#\n\x1f\x45GRESS_ENFORCEMENT_GUEST_ROUTES\x10\x02\x12-\n)EGRESS_ENFORCEMENT_GUEST_ROUTES_AND_PROXY\x10\x03\x32\xa0\x01\n\x0eNetworkService\x12I\n\rUpdateNetwork\x12\x1f.rayito.v1.UpdateNetworkRequest\x1a\x17.rayito.v1.NetworkState\x12\x43\n\nGetNetwork\x12\x1c.rayito.v1.GetNetworkRequest\x1a\x17.rayito.v1.NetworkStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rayito.v1.network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EGRESSENFORCEMENT']._serialized_start=658
  _globals['_EGRESSENFORCEMENT']._serialized_end=826
  _globals['_EGRESSPROXY']._serialized_start=39
  _globals['_EGRESSPROXY']._serialized_end=170
  _globals['_NETWORKPOLICY']._serialized_start=173
  _globals['_NETWORKPOLICY']._serialized_end=325
  _globals['_UPDATENETWORKREQUEST']._serialized_start=327
  _globals['_UPDATENETWORKREQUEST']._serialized_end=399
  _globals['_GETNETWORKREQUEST']._serialized_start=401
  _globals['_GETNETWORKREQUEST']._serialized_end=420
  _globals['_NETWORKSTATE']._serialized_start=423
  _globals['_NETWORKSTATE']._serialized_end=655
  _globals['_NETWORKSERVICE']._serialized_start=829
  _globals['_NETWORKSERVICE']._serialized_end=989
# @@protoc_insertion_point(module_scope)
