# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import network_pb2 as rayito_dot_v1_dot_network__pb2


class NetworkServiceStub:
    """Política de egress dentro del guest (ADR-012). Sólo se aplica en imágenes
    con CAP_NET_ADMIN (rayito-base-caps); nunca filtra el tráfico del propio
    rayd (root). Los dos RPCs exigen x-access-token.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateNetwork = channel.unary_unary(
                '/rayito.v1.NetworkService/UpdateNetwork',
                request_serializer=rayito_dot_v1_dot_network__pb2.UpdateNetworkRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_network__pb2.NetworkState.FromString,
                _registered_method=True)
        self.GetNetwork = channel.unary_unary(
                '/rayito.v1.NetworkService/GetNetwork',
                request_serializer=rayito_dot_v1_dot_network__pb2.GetNetworkRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_network__pb2.NetworkState.FromString,
                _registered_method=True)


class NetworkServiceServicer:
    """Política de egress dentro del guest (ADR-012). Sólo se aplica en imágenes
    con CAP_NET_ADMIN (rayito-base-caps); nunca filtra el tráfico del propio
    rayd (root). Los dos RPCs exigen x-access-token.
    """

    def UpdateNetwork(self, request, context):
        """Sustituye la política entera de forma atómica (semántica de
        update_network de E2B: lo omitido se borra) y afecta a las conexiones
        nuevas. INVALID_ARGUMENT si una entrada o el proxy están mal formados;
        FAILED_PRECONDITION si la política exige restringir y la imagen no tiene
        CAP_NET_ADMIN; INTERNAL si la instalación o la verificación fallan (rayd
        deja deny-all instalado).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetwork(self, request, context):
        """Estado actual; nunca devuelve la dirección ni las credenciales del proxy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNetwork,
                    request_deserializer=rayito_dot_v1_dot_network__pb2.UpdateNetworkRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_network__pb2.NetworkState.SerializeToString,
            ),
            'GetNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetwork,
                    request_deserializer=rayito_dot_v1_dot_network__pb2.GetNetworkRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_network__pb2.NetworkState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.NetworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.NetworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NetworkService:
    """Política de egress dentro del guest (ADR-012). Sólo se aplica en imágenes
    con CAP_NET_ADMIN (rayito-base-caps); nunca filtra el tráfico del propio
    rayd (root). Los dos RPCs exigen x-access-token.
    """

    @staticmethod
    def UpdateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.NetworkService/UpdateNetwork',
            rayito_dot_v1_dot_network__pb2.UpdateNetworkRequest.SerializeToString,
            rayito_dot_v1_dot_network__pb2.NetworkState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.NetworkService/GetNetwork',
            rayito_dot_v1_dot_network__pb2.GetNetworkRequest.SerializeToString,
            rayito_dot_v1_dot_network__pb2.NetworkState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
