# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import process_pb2 as rayito_dot_v1_dot_process__pb2


class ProcessServiceStub:
    """Ejecución de comandos arbitrarios dentro del sandbox.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_stream(
                '/rayito.v1.ProcessService/Start',
                request_serializer=rayito_dot_v1_dot_process__pb2.StartRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.ProcessEvent.FromString,
                _registered_method=True)
        self.Connect = channel.unary_stream(
                '/rayito.v1.ProcessService/Connect',
                request_serializer=rayito_dot_v1_dot_process__pb2.ConnectRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.ProcessEvent.FromString,
                _registered_method=True)
        self.SendInput = channel.unary_unary(
                '/rayito.v1.ProcessService/SendInput',
                request_serializer=rayito_dot_v1_dot_process__pb2.SendInputRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.SendInputResponse.FromString,
                _registered_method=True)
        self.CloseStdin = channel.unary_unary(
                '/rayito.v1.ProcessService/CloseStdin',
                request_serializer=rayito_dot_v1_dot_process__pb2.CloseStdinRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.CloseStdinResponse.FromString,
                _registered_method=True)
        self.SendSignal = channel.unary_unary(
                '/rayito.v1.ProcessService/SendSignal',
                request_serializer=rayito_dot_v1_dot_process__pb2.SendSignalRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.SendSignalResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/rayito.v1.ProcessService/List',
                request_serializer=rayito_dot_v1_dot_process__pb2.ListRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.ListResponse.FromString,
                _registered_method=True)


class ProcessServiceServicer:
    """Ejecución de comandos arbitrarios dentro del sandbox.
    """

    def Start(self, request, context):
        """Lanza un proceso y transmite su salida. El primer mensaje del stream es
        siempre un StartEvent con el PID; después vienen DataEvent hasta EndEvent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Se engancha al stream de un proceso ya en marcha (background) o terminado
        hace menos de 30 s (se reenvían StartEvent + EndEvent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInput(self, request, context):
        """Escribe en el stdin de un proceso vivo (sólo si se lanzó con stdin=true).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseStdin(self, request, context):
        """Cierra el stdin (EOF) de un proceso lanzado con stdin=true.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSignal(self, request, context):
        """Envía una señal al grupo de procesos (SIGTERM, SIGKILL, ...).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Lista procesos y PTYs activos.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_stream_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.StartRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.ProcessEvent.SerializeToString,
            ),
            'Connect': grpc.unary_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.ConnectRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.ProcessEvent.SerializeToString,
            ),
            'SendInput': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInput,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.SendInputRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.SendInputResponse.SerializeToString,
            ),
            'CloseStdin': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseStdin,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.CloseStdinRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.CloseStdinResponse.SerializeToString,
            ),
            'SendSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSignal,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.SendSignalRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.SendSignalResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.ListRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.ProcessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.ProcessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessService:
    """Ejecución de comandos arbitrarios dentro del sandbox.
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.ProcessService/Start',
            rayito_dot_v1_dot_process__pb2.StartRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.ProcessEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.ProcessService/Connect',
            rayito_dot_v1_dot_process__pb2.ConnectRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.ProcessEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.ProcessService/SendInput',
            rayito_dot_v1_dot_process__pb2.SendInputRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.SendInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseStdin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.ProcessService/CloseStdin',
            rayito_dot_v1_dot_process__pb2.CloseStdinRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.CloseStdinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.ProcessService/SendSignal',
            rayito_dot_v1_dot_process__pb2.SendSignalRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.SendSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.ProcessService/List',
            rayito_dot_v1_dot_process__pb2.ListRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
