# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rayito.v1 import process_pb2 as rayito_dot_v1_dot_process__pb2
from rayito.v1 import pty_pb2 as rayito_dot_v1_dot_pty__pb2


class PtyServiceStub:
    """Terminal interactiva real (pseudo-terminal), no un proceso con pipes.

    Forma server-stream + unarios (la misma que envd de E2B): no depende de que el
    proxy de AWS soporte streams bidireccionales y permite que la PTY comparta el
    handle de comando del SDK.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_stream(
                '/rayito.v1.PtyService/Create',
                request_serializer=rayito_dot_v1_dot_pty__pb2.PtyStart.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_pty__pb2.PtyServerMessage.FromString,
                _registered_method=True)
        self.Connect = channel.unary_stream(
                '/rayito.v1.PtyService/Connect',
                request_serializer=rayito_dot_v1_dot_process__pb2.ConnectRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_pty__pb2.PtyServerMessage.FromString,
                _registered_method=True)
        self.SendInput = channel.unary_unary(
                '/rayito.v1.PtyService/SendInput',
                request_serializer=rayito_dot_v1_dot_process__pb2.SendInputRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_process__pb2.SendInputResponse.FromString,
                _registered_method=True)
        self.Resize = channel.unary_unary(
                '/rayito.v1.PtyService/Resize',
                request_serializer=rayito_dot_v1_dot_pty__pb2.ResizeRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_pty__pb2.ResizeResponse.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/rayito.v1.PtyService/Kill',
                request_serializer=rayito_dot_v1_dot_pty__pb2.KillPtyRequest.SerializeToString,
                response_deserializer=rayito_dot_v1_dot_pty__pb2.KillPtyResponse.FromString,
                _registered_method=True)


class PtyServiceServicer:
    """Terminal interactiva real (pseudo-terminal), no un proceso con pipes.

    Forma server-stream + unarios (la misma que envd de E2B): no depende de que el
    proxy de AWS soporte streams bidireccionales y permite que la PTY comparta el
    handle de comando del SDK.
    """

    def Create(self, request, context):
        """El primer mensaje del stream es siempre PtyStarted{pid}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Se reengancha a una PTY viva tras disconnect() o suspend/resume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PtyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_stream_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=rayito_dot_v1_dot_pty__pb2.PtyStart.FromString,
                    response_serializer=rayito_dot_v1_dot_pty__pb2.PtyServerMessage.SerializeToString,
            ),
            'Connect': grpc.unary_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.ConnectRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_pty__pb2.PtyServerMessage.SerializeToString,
            ),
            'SendInput': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInput,
                    request_deserializer=rayito_dot_v1_dot_process__pb2.SendInputRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_process__pb2.SendInputResponse.SerializeToString,
            ),
            'Resize': grpc.unary_unary_rpc_method_handler(
                    servicer.Resize,
                    request_deserializer=rayito_dot_v1_dot_pty__pb2.ResizeRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_pty__pb2.ResizeResponse.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=rayito_dot_v1_dot_pty__pb2.KillPtyRequest.FromString,
                    response_serializer=rayito_dot_v1_dot_pty__pb2.KillPtyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rayito.v1.PtyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rayito.v1.PtyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PtyService:
    """Terminal interactiva real (pseudo-terminal), no un proceso con pipes.

    Forma server-stream + unarios (la misma que envd de E2B): no depende de que el
    proxy de AWS soporte streams bidireccionales y permite que la PTY comparta el
    handle de comando del SDK.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.PtyService/Create',
            rayito_dot_v1_dot_pty__pb2.PtyStart.SerializeToString,
            rayito_dot_v1_dot_pty__pb2.PtyServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rayito.v1.PtyService/Connect',
            rayito_dot_v1_dot_process__pb2.ConnectRequest.SerializeToString,
            rayito_dot_v1_dot_pty__pb2.PtyServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.PtyService/SendInput',
            rayito_dot_v1_dot_process__pb2.SendInputRequest.SerializeToString,
            rayito_dot_v1_dot_process__pb2.SendInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.PtyService/Resize',
            rayito_dot_v1_dot_pty__pb2.ResizeRequest.SerializeToString,
            rayito_dot_v1_dot_pty__pb2.ResizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rayito.v1.PtyService/Kill',
            rayito_dot_v1_dot_pty__pb2.KillPtyRequest.SerializeToString,
            rayito_dot_v1_dot_pty__pb2.KillPtyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
