# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rayito/v1/s3_mounts.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'rayito/v1/s3_mounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19rayito/v1/s3_mounts.proto\x12\trayito.v1\"\x10\n\x0eS3MountsConfig\"\x10\n\x0eS3MountsStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rayito.v1.s3_mounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_S3MOUNTSCONFIG']._serialized_start=40
  _globals['_S3MOUNTSCONFIG']._serialized_end=56
  _globals['_S3MOUNTSSTATUS']._serialized_start=58
  _globals['_S3MOUNTSSTATUS']._serialized_end=74
# @@protoc_insertion_point(module_scope)
