"""Where ``THIRD_PARTY_LICENSES.md`` comes from (generated by
``make licenses``, which every ``make image-licenses`` and CI run, and never
committed) and ``check_third_party_licenses.py`` on synthetic inputs: the
notices and the ``cargo tree`` graph must be the same set (workspace crates skipped), every listed crate must be
in the binary's ``.dep-v0`` (a superset), and a listed crate shipping a
``NOTICE`` file fails until the root ``NOTICE`` names it."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

SCRIPTS = Path(__file__).resolve().parents[1]
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import check_third_party_licenses as notices
from test_check_auditable import auditable_elf

REPO_ROOT = SCRIPTS.parent
NOTICES_FILE = "THIRD_PARTY_LICENSES.md"
CI_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "ci.yml"
NOTICES = """# Third-party licenses of rayd

### MIT License (`MIT`)

Used by:

- `tokio 1.53.1` <https://github.com/tokio-rs/tokio>
- `axum 0.8.9`

```text
MIT text
```
"""


def graph(*extra: dict[str, object]) -> list[dict[str, object]]:
    return [
        {"name": "rayd", "version": "0.7.0", "source": "local", "root": True},
        {"name": "rayd-core", "version": "0.7.0", "source": "local"},
        {"name": "tokio", "version": "1.53.1", "source": "crates.io"},
        {"name": "axum", "version": "0.8.9", "source": "crates.io"},
        {"name": "cc", "version": "1.2.0", "source": "crates.io", "kind": "build"},
        *extra,
    ]


def write(tmp_path: Path, name: str, content: str | bytes) -> Path:
    path = tmp_path / name
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")
    return path


def test_the_notices_file_is_generated_never_committed() -> None:
    """Committed, it went stale on every ``Cargo.lock`` bump (Dependabot
    included) and needed a privileged bot or a manual commit to catch up."""
    tracked = subprocess.run(
        ["git", "ls-files", "--", NOTICES_FILE],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    assert tracked == ""
    gitignore = (REPO_ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    assert f"/{NOTICES_FILE}" in gitignore


def makefile_prerequisites(target: str) -> list[str]:
    makefile = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    match = re.search(rf"^{re.escape(target)}:(.*)$", makefile, re.MULTILINE)
    assert match, target
    return match.group(1).split()


def test_staging_the_notices_always_regenerates_them() -> None:
    assert "licenses" in makefile_prerequisites("image-licenses")
    makefile = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    zip_targets = re.findall(r"^(image-zip[\w-]*):", makefile, re.MULTILINE)
    assert zip_targets
    for target in zip_targets:
        assert "image-licenses" in makefile_prerequisites(target), target


def test_ci_generates_the_notices_before_checking_and_zipping_them() -> None:
    build = yaml.safe_load(CI_WORKFLOW.read_text(encoding="utf-8"))["jobs"]["build"]
    runs = [step.get("run", "") for step in build["steps"]]

    def index(fragment: str) -> int:
        return next(i for i, run in enumerate(runs) if fragment in run)

    generated = index("make image-licenses")
    assert generated < index("check_third_party_licenses.py") < index("image_zip.py")
    for workflow in (REPO_ROOT / ".github" / "workflows").glob("*.yml"):
        assert "licenses-check" not in workflow.read_text(encoding="utf-8"), workflow


TREE = """axum v0.8.9
rayd-core v0.7.0 (/work/crates/rayd-core)
tokio v1.53.1
async-trait v0.1.92 (proc-macro)
tokio v1.53.1 (*)
"""


def test_tree_coverage_passes_and_skips_path_dependencies(tmp_path: Path) -> None:
    md = write(
        tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES + "- `async-trait 0.1.92`\n"
    )
    tree = write(tmp_path, "tree.txt", TREE)
    assert notices.check(md, None, None, tree_path=tree) == 3


def test_a_compiled_crate_missing_from_the_notices_fails(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES)
    tree = write(tmp_path, "tree.txt", TREE)
    assert notices.main([str(md), "--tree", str(tree)]) == 1
    assert (
        "async-trait 0.1.92: compiled into rayd but not listed"
        in capsys.readouterr().err
    )


def test_a_stale_extra_entry_fails(tmp_path: Path) -> None:
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES + "- `ring 0.17.14`\n")
    tree = write(
        tmp_path, "tree.txt", TREE.replace("async-trait v0.1.92 (proc-macro)\n", "")
    )
    with pytest.raises(
        notices.NoticesError, match=r"ring 0\.17\.14: listed but not compiled"
    ):
        notices.check(md, None, None, tree_path=tree)


def test_a_version_drift_fails(tmp_path: Path) -> None:
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES.replace("1.53.1", "1.52.0"))
    tree = write(tmp_path, "tree.txt", "axum v0.8.9\ntokio v1.53.1\n")
    with pytest.raises(notices.NoticesError, match=r"tokio 1\.53\.1: compiled"):
        notices.check(md, None, None, tree_path=tree)


def test_the_binary_records_every_listed_crate(tmp_path: Path) -> None:
    """``.dep-v0`` is a superset (dev-dependency features unify in ``cargo
    metadata``), so an extra recorded crate such as ``ring`` passes."""
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES)
    extra = {"name": "ring", "version": "0.17.14", "source": "crates.io"}
    binary = write(tmp_path, "rayd", auditable_elf(graph(extra)))
    assert notices.check(md, binary, None) == 2


def test_a_listed_crate_absent_from_the_binary_fails(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES + "- `serde 1.0.228`\n")
    binary = write(tmp_path, "rayd", auditable_elf(graph()))
    assert notices.main([str(md), "--binary", str(binary)]) == 1
    assert "serde 1.0.228: listed but absent from the .dep-v0 of rayd" in (
        capsys.readouterr().err
    )


def test_an_empty_file_fails(tmp_path: Path) -> None:
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", "# nothing\n")
    with pytest.raises(notices.NoticesError, match="lists no crate"):
        notices.check(md, None, None)


def metadata_with_notice(tmp_path: Path) -> Path:
    crate_dir = tmp_path / "registry" / "axum-0.8.9"
    crate_dir.mkdir(parents=True)
    (crate_dir / "Cargo.toml").write_text("[package]\n", encoding="utf-8")
    (crate_dir / "NOTICE").write_text("axum notice\n", encoding="utf-8")
    plain_dir = tmp_path / "registry" / "tokio-1.53.1"
    plain_dir.mkdir(parents=True)
    (plain_dir / "Cargo.toml").write_text("[package]\n", encoding="utf-8")
    metadata = {
        "packages": [
            {
                "name": "axum",
                "version": "0.8.9",
                "manifest_path": str(crate_dir / "Cargo.toml"),
            },
            {
                "name": "tokio",
                "version": "1.53.1",
                "manifest_path": str(plain_dir / "Cargo.toml"),
            },
        ]
    }
    return write(tmp_path, "metadata.json", json.dumps(metadata))


def test_a_crate_notice_file_must_be_carried_in_the_root_notice(tmp_path: Path) -> None:
    md = write(tmp_path, "THIRD_PARTY_LICENSES.md", NOTICES)
    metadata = metadata_with_notice(tmp_path)
    bare = write(tmp_path, "NOTICE", "Rayito\nmentions axum-extra only\n")
    with pytest.raises(notices.NoticesError, match=r"axum 0\.8\.9 ships NOTICE"):
        notices.check(md, None, metadata, bare)
    carried = write(tmp_path, "NOTICE", "Rayito\n- axum 0.8.9: axum notice\n")
    assert notices.check(md, None, metadata, carried) == 2
