"""Verify that ``THIRD_PARTY_LICENSES.md`` covers what ``rayd`` really ships.

``make licenses`` generates the notices file with cargo-about from
``Cargo.lock`` (``about.toml``, ``about.hbs``), and ``make licenses-check``
proves the committed copy is not stale. This script closes the two gaps a
regeneration alone cannot see, with the standard library only:

- ``--binary``: every third-party crate that the ``rayd`` binary embeds in
  its ``.dep-v0`` section (``cargo auditable``; read by
  ``scripts/check_auditable.py``) and that is linked at run time is listed in
  the notices file at the same version. Build-time packages (``kind:
  build``: build scripts and proc macros) and the workspace's own crates
  (any source other than ``crates.io``) are not distributed in the binary
  and are skipped. A crate the cargo-about graph missed fails here.
- ``--metadata``: the JSON of ``cargo metadata --format-version 1`` for the
  workspace. A listed crate whose source directory carries a ``NOTICE`` file
  (Apache-2.0 §4(d): its text must travel with the binary) fails unless the
  root ``NOTICE`` names the crate, because cargo-about only collects licence
  texts, never ``NOTICE`` files.

Usage::

    python3 scripts/check_third_party_licenses.py THIRD_PARTY_LICENSES.md \\
        --binary target/aarch64-unknown-linux-musl/release/rayd \\
        --metadata cargo-metadata.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import check_auditable

CRATE_LINE = re.compile(
    r"^- `(?P<name>[A-Za-z0-9_.-]+) (?P<version>[^`\s]+)`", re.MULTILINE
)
REGISTRY_SOURCE = "crates.io"
BUILD_KIND = "build"
NOTICE_PREFIX = "notice"
ROOT_NOTICE = Path(__file__).resolve().parents[1] / "NOTICE"


class NoticesError(Exception):
    """A coverage failure; the message names every offending crate."""


def listed_crates(notices: str) -> set[tuple[str, str]]:
    """The ``(name, version)`` pairs the generated file lists."""
    crates = {
        (match["name"], match["version"]) for match in CRATE_LINE.finditer(notices)
    }
    if not crates:
        raise NoticesError(
            "the notices file lists no crate: was it generated by `make licenses`?"
        )
    return crates


def shipped_crates(packages: list[dict[str, Any]]) -> set[tuple[str, str]]:
    """Third-party crates linked into the binary at run time, from ``.dep-v0``."""
    return {
        (str(package["name"]), str(package["version"]))
        for package in packages
        if package.get("source") == REGISTRY_SOURCE
        and package.get("kind", "runtime") != BUILD_KIND
        and not package.get("root", False)
    }


def missing_from_notices(
    shipped: set[tuple[str, str]], listed: set[tuple[str, str]]
) -> list[str]:
    return sorted(f"{name} {version}" for name, version in shipped - listed)


def crates_with_notice_files(
    metadata: dict[str, Any], listed: set[tuple[str, str]]
) -> dict[str, list[str]]:
    """Listed crates whose source directory ships a ``NOTICE*`` file, by
    ``"<name> <version>"``, with the file names found."""
    found: dict[str, list[str]] = {}
    for package in metadata.get("packages", []):
        key = (str(package.get("name")), str(package.get("version")))
        if key not in listed:
            continue
        directory = Path(str(package.get("manifest_path", ""))).parent
        if not directory.is_dir():
            continue
        notices = sorted(
            entry.name
            for entry in directory.iterdir()
            if entry.is_file() and entry.name.lower().startswith(NOTICE_PREFIX)
        )
        if notices:
            found[f"{key[0]} {key[1]}"] = notices
    return found


def unreproduced_notices(found: dict[str, list[str]], root_notice: str) -> list[str]:
    return sorted(
        f"{crate} ships {', '.join(files)}"
        for crate, files in found.items()
        if not re.search(
            rf"(?<![\w-]){re.escape(crate.split(' ', 1)[0])}(?![\w-])", root_notice
        )
    )


def check(
    notices_path: Path,
    binary: Path | None,
    metadata_path: Path | None,
    root_notice_path: Path = ROOT_NOTICE,
) -> int:
    listed = listed_crates(notices_path.read_text(encoding="utf-8"))
    problems: list[str] = []
    if binary is not None:
        packages = check_auditable.embedded_packages(binary.read_bytes())
        missing = missing_from_notices(shipped_crates(packages), listed)
        problems += [
            f"{crate}: linked into {binary.name} but not listed" for crate in missing
        ]
    if metadata_path is not None:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        found = crates_with_notice_files(metadata, listed)
        root_notice = root_notice_path.read_text(encoding="utf-8")
        problems += [
            f"{line}: carry its text in the root NOTICE (Apache-2.0 §4(d))"
            for line in unreproduced_notices(found, root_notice)
        ]
    if problems:
        raise NoticesError("\n".join(problems))
    return len(listed)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("notices", type=Path, help="THIRD_PARTY_LICENSES.md")
    parser.add_argument("--binary", type=Path, help="rayd built with `cargo auditable`")
    parser.add_argument(
        "--metadata", type=Path, help="output of `cargo metadata --format-version 1`"
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        count = check(args.notices, args.binary, args.metadata)
    except (NoticesError, check_auditable.AuditableError) as exc:
        print(f"check_third_party_licenses: {exc}", file=sys.stderr)
        return 1
    print(f"{args.notices}: {count} crates listed, coverage ok")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
