"""Render the agent template's package data into the TypeScript SDK
(ai-agent-fast-start, design.md §5).

Single source: ``clients/python/src/rayito/_agent/_assets/`` (the
hash-locked ``requirements-deepagents.txt`` and the ``rayito-agent-prefetch``
daemon), which the Python SDK ships as package data. Output, deterministic:
``clients/typescript/src/agent/assets/template-assets.gen.ts`` with both
files as string constants, so ``AgentTemplate`` writes the same build
context in both SDKs.

Usage::

    python scripts/gen_agent_template_assets.py           # render
    python scripts/gen_agent_template_assets.py --check   # exit 1 on drift
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = REPO_ROOT / "clients" / "python" / "src" / "rayito" / "_agent" / "_assets"
TARGET = (
    REPO_ROOT
    / "clients"
    / "typescript"
    / "src"
    / "agent"
    / "assets"
    / "template-assets.gen.ts"
)
CONSTANTS = (
    ("DEEPAGENTS_REQUIREMENTS", "requirements-deepagents.txt"),
    ("PREFETCH_SCRIPT", "rayito-agent-prefetch"),
)
HEADER = (
    "// GENERATED by scripts/gen_agent_template_assets.py from\n"
    "// clients/python/src/rayito/_agent/_assets/. Do not edit by hand: run\n"
    "// `python scripts/gen_agent_template_assets.py`.\n"
)


def ts_string_literal(text: str) -> str:
    """A template literal, escaped like `gen_stack_assets.py` does: biome
    keeps it as is, so the output passes `pnpm lint` untouched."""
    escaped = text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f"`{escaped}`"


def render() -> str:
    parts = [HEADER]
    for constant, name in CONSTANTS:
        text = (ASSETS_DIR / name).read_text(encoding="utf-8")
        parts.append(f"export const {constant} = {ts_string_literal(text)};\n")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    expected = render()
    if "--check" in argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            print(
                f"gen_agent_template_assets: {TARGET.relative_to(REPO_ROOT)} is stale; run the script"
            )
            return 1
        print("gen_agent_template_assets: OK")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"gen_agent_template_assets: wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
