"""Render the SDK limits modules from ``limits.json`` (single source).

``limits.json`` at the repository root holds every Lambda MicroVMs limit the
SDKs validate client-side (``AWS_API_NOTES.md`` §2, §3, §6, §11). This script
renders it into ``clients/python/src/rayito/_limits.py`` and
``clients/typescript/src/limits.ts`` deterministically, formatted the way
``ruff format`` and ``biome format`` expect (100 columns, trailing commas),
so neither SDK can drift from the other. Standard library only.

Usage::

    python scripts/gen_limits.py           # rewrite both modules
    python scripts/gen_limits.py --check   # exit 1 with a diff on drift
"""

from __future__ import annotations

import difflib
import json
import re
import sys
from collections.abc import Iterable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LIMITS_JSON = REPO_ROOT / "limits.json"
PYTHON_TARGET = REPO_ROOT / "clients" / "python" / "src" / "rayito" / "_limits.py"
TYPESCRIPT_TARGET = REPO_ROOT / "clients" / "typescript" / "src" / "limits.ts"
LINE_WIDTH = 100
INDENT = "    "
TS_INDENT = "  "

SET_KEYS = frozenset({"terminalStates", "suspendedStates", "managedNetworkConnectors"})
GROUPS: tuple[tuple[str, ...], ...] = (
    (
        "maxDurationSeconds",
        "minDurationSeconds",
        "idleMaxIdleMinSeconds",
        "idleSuspendedMinSeconds",
    ),
    (
        "tokenTtlMinutes",
        "tokenTtlMinMinutes",
        "tokenRefreshAfterMinutes",
        "tokenRefreshRetrySeconds",
    ),
    (
        "runHookPayloadMaxChars",
        "clientTokenMax",
        "microvmIdMinLength",
        "microvmIdMaxLength",
        "listMaxResults",
        "networkConnectorsMax",
    ),
    (
        "defaultPort",
        "hooksPort",
        "portMin",
        "portMax",
        "endpointTlsPort",
        "hookPathPrefix",
    ),
    ("maxConcurrentConnections1Vcpu",),
    ("microvmStates", "terminalStates", "suspendedStates"),
    ("managedNetworkConnectors",),
    ("supportedRegions",),
    ("apiTps",),
    (
        "persistKeyPrefixMaxBytes",
        "persistExcludeMax",
        "s3BucketNameMin",
        "s3BucketNameMax",
        "defaultPersistTimeoutSeconds",
    ),
)

PYTHON_HEADER = '''"""Límites y cuotas de Lambda MicroVMs que el SDK valida en cliente.

GENERADO por `scripts/gen_limits.py` desde `limits.json` (raíz del repo): no
editar a mano, ejecutar `make limits`. Fuente de los valores:
`AWS_API_NOTES.md` §2, §3, §6, §11 y `docs/aws-api/model_summary.md`.
Nada aquí es configurable por el usuario: son propiedades de la API.
"""

from __future__ import annotations

from typing import Final
'''

TYPESCRIPT_HEADER = """// GENERATED by scripts/gen_limits.py from limits.json (repository root).
// Do not edit by hand: run `make limits`. Values come from AWS_API_NOTES.md
// §2, §3, §6, §11. Nothing here is user-configurable: these are API facts.
"""


CONSTANT_NAME_OVERRIDES = {
    "s3BucketNameMin": "S3_BUCKET_NAME_MIN",
    "s3BucketNameMax": "S3_BUCKET_NAME_MAX",
}


def constant_name(key: str) -> str:
    """``maxConcurrentConnections1Vcpu`` -> ``MAX_CONCURRENT_CONNECTIONS_1_VCPU``;
    a service name that carries its own digit (``s3``) keeps it attached."""
    if key in CONSTANT_NAME_OVERRIDES:
        return CONSTANT_NAME_OVERRIDES[key]
    with_digits = re.sub(r"([a-zA-Z])(\d)", r"\1_\2", key)
    with_words = re.sub(r"(\d)([a-zA-Z])", r"\1_\2", with_digits)
    snake = re.sub(r"([a-z])([A-Z])", r"\1_\2", with_words)
    return snake.upper()


def load_limits() -> dict[str, object]:
    with LIMITS_JSON.open(encoding="utf-8") as handle:
        limits = json.load(handle)
    listed = {key for group in GROUPS for key in group}
    unknown = sorted(set(limits) - listed)
    missing = sorted(listed - set(limits))
    if unknown or missing:
        raise SystemExit(
            f"limits.json: claves desconocidas {unknown}, ausentes {missing}"
        )
    return limits


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


# --------------------------------------------------------------------- python


def python_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, str):
        return quoted(value)
    raise TypeError(f"valor no soportado en limits.json: {value!r}")


def python_collection(
    prefix: str, items: Iterable[str], opening: str, closing: str
) -> str:
    """Ruff style: one line if it fits, otherwise one element per line with a
    trailing comma (the magic trailing comma keeps it exploded)."""
    elements = list(items)
    single = f"{prefix}{opening}{', '.join(elements)}{closing}"
    if len(single) <= LINE_WIDTH:
        return single
    body = "".join(f"{INDENT}{element},\n" for element in elements)
    return f"{prefix}{opening}\n{body}{closing}"


def python_frozenset(name: str, values: list[str]) -> str:
    elements = [quoted(value) for value in values]
    prefix = f"{name}: Final = frozenset("
    single = f"{prefix}{{{', '.join(elements)}}})"
    if len(single) <= LINE_WIDTH:
        return single
    inner = f"{INDENT}{{{', '.join(elements)}}}"
    if len(inner) <= LINE_WIDTH:
        return f"{prefix}\n{inner}\n)"
    body = "".join(f"{INDENT}{INDENT}{element},\n" for element in elements)
    return f"{prefix}\n{INDENT}{{\n{body}{INDENT}}}\n)"


def python_line(key: str, value: object) -> str:
    name = constant_name(key)
    if isinstance(value, dict):
        items = [
            f"{quoted(item)}: {python_scalar(value[item])}" for item in sorted(value)
        ]
        return python_collection(f"{name}: Final[dict[str, int]] = ", items, "{", "}")
    if isinstance(value, list):
        elements = [quoted(str(item)) for item in value]
        if key in SET_KEYS:
            return python_frozenset(name, [str(item) for item in value])
        if len(elements) == 1:
            return f"{name}: Final = ({elements[0]},)"
        return python_collection(f"{name}: Final = ", elements, "(", ")")
    return f"{name}: Final = {python_scalar(value)}"


def render_python(limits: dict[str, object]) -> str:
    blocks = [
        "\n".join(python_line(key, limits[key]) for key in group) for group in GROUPS
    ]
    return PYTHON_HEADER + "\n" + "\n\n".join(blocks) + "\n"


# ----------------------------------------------------------------- typescript


def ts_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, str):
        return quoted(value)
    raise TypeError(f"valor no soportado en limits.json: {value!r}")


def ts_collection(
    prefix: str, items: list[str], opening: str, closing: str, suffix: str
) -> str:
    """Biome style: one line if it fits, otherwise one element per line."""
    single = f"{prefix}{opening}{', '.join(items)}{closing}{suffix}"
    if len(single) <= LINE_WIDTH:
        return single
    body = "".join(f"{TS_INDENT}{item},\n" for item in items)
    return f"{prefix}{opening}\n{body}{closing}{suffix}"


def ts_line(key: str, value: object) -> str:
    name = constant_name(key)
    if isinstance(value, dict):
        items = [f"{item}: {ts_scalar(value[item])}" for item in sorted(value)]
        prefix = f"export const {name}: Readonly<Record<string, number>> = "
        return ts_collection(prefix, items, "{", "}", ";")
    if isinstance(value, list):
        elements = [quoted(str(item)) for item in value]
        if key in SET_KEYS:
            prefix = f"export const {name}: ReadonlySet<string> = new Set("
            return ts_collection(prefix, elements, "[", "]", ");")
        return ts_collection(
            f"export const {name} = ", elements, "[", "]", " as const;"
        )
    return f"export const {name} = {ts_scalar(value)} as const;"


def render_typescript(limits: dict[str, object]) -> str:
    blocks = ["\n".join(ts_line(key, limits[key]) for key in group) for group in GROUPS]
    return TYPESCRIPT_HEADER + "\n" + "\n\n".join(blocks) + "\n"


# ----------------------------------------------------------------------- main


def current_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def check(renders: dict[Path, str]) -> int:
    drifted = 0
    for path, expected in renders.items():
        actual = current_text(path)
        if actual == expected:
            continue
        drifted += 1
        relative = path.relative_to(REPO_ROOT).as_posix()
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{relative} (on disk)",
            tofile=f"{relative} (from limits.json)",
        )
        sys.stdout.write(f"gen_limits: {relative} drifts from limits.json\n")
        sys.stdout.writelines(diff)
    if drifted:
        sys.stdout.write(
            "gen_limits: run `python scripts/gen_limits.py` to regenerate\n"
        )
    return 1 if drifted else 0


def main(argv: list[str]) -> int:
    limits = load_limits()
    renders = {
        PYTHON_TARGET: render_python(limits),
        TYPESCRIPT_TARGET: render_typescript(limits),
    }
    if "--check" in argv:
        return check(renders)
    for path, text in renders.items():
        write_text(path, text)
        sys.stdout.write(
            f"gen_limits: wrote {path.relative_to(REPO_ROOT).as_posix()}\n"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
