// GENERATED by scripts/gen_stack_assets.py from infra/custom-domain.yaml.
// Do not edit by hand: run `python scripts/gen_stack_assets.py`.
export const TEMPLATE_BODY = `AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Rayito m15-custom-domain (optional, experimental): a CloudFront distribution
  with a wildcard alias, its viewer-request CloudFront Function (dynamic
  per-request origin selection via cf.updateRequestOrigin, runtime
  cloudfront-js-2.0) and the CloudFront KeyValueStore it reads routes from.
  No Lambda, no VPC, no IAM role beyond what CloudFront itself needs
  (CAPABILITY_NAMED_IAM is NOT required by this template; kept for parity
  with other OptionalStack components only if a future Lambda refresher is
  added). Parameters and actions: AWS_API_NOTES.md section 29. Deploy it only
  if you use domain=/CustomDomain; delete the stack to remove the
  distribution, the Function and the KeyValueStore (no sandbox data is ever
  stored in the KVS, only ephemeral routing entries).

Parameters:
  PublicDomain:
    Type: String
    MinLength: 1
    Description: >-
      Your own domain (D3, maintainer-owned). The distribution's alias is
      *.<PublicDomain>; CustomDomain(public_domain=PublicDomain) computes
      per-sandbox hostnames under it.
  CertificateArn:
    Type: String
    MinLength: 1
    AllowedPattern: "^arn:aws[a-zA-Z-]*:acm:us-east-1:[0-9]{12}:certificate/.+$"
    Description: >-
      ARN of an ACM certificate in us-east-1 covering *.<PublicDomain>
      (CloudFront requires us-east-1 certificates regardless of the
      distribution's own region).

Resources:
  RouteKeyValueStore:
    Type: AWS::CloudFront::KeyValueStore
    Properties:
      Name: !Sub "rayito-custom-domain-\${AWS::StackName}"
      Comment: >-
        Rayito custom-domain routes: j:<port>-<alias> / m:<port>-<alias>.
        See infra/custom-domain.yaml.

  RouterFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "rayito-custom-domain-router-\${AWS::StackName}"
      FunctionConfig:
        Comment: >-
          Rayito custom-domain router: strips any viewer x-aws-proxy-*
          header, checks the route's traffic token (constant-time) and
          calls cf.updateRequestOrigin() with the sandbox's endpoint and
          the proxy headers it expects. Source of truth:
          infra/functions/custom_domain_router.js (kept byte-identical by
          scripts/tests/test_custom_domain_function_sync.py).
        Runtime: cloudfront-js-2.0
        KeyValueStoreAssociations:
          - KeyValueStoreARN: !GetAtt RouteKeyValueStore.Arn
      AutoPublish: true
      FunctionCode: |
        // Rayito m15-custom-domain: enrutado dinámico de CloudFront por sandbox.
        //
        // Asociada como evento \`viewer-request\` (único evento donde CloudFront
        // permite \`cf.updateRequestOrigin\`, ver AWS_API_NOTES.md §29). Runtime
        // \`cloudfront-js-2.0\` (exigido por el helper de KVS y por
        // \`cf.updateRequestOrigin\`). El KeyValueStore asociado guarda dos claves
        // por ruta (\`_custom_domain/_domain.py\` del SDK):
        //   j:<puerto>-<alias>  -> el JWE vigente de \`create-microvm-auth-token\`
        //   m:<puerto>-<alias>  -> JSON compacto {"e": endpoint, "t": sha256(token) o "", "x": exp}
        //
        // Pasos (arquitectura M15 §7.8): (1) borra cualquier cabecera
        // \`x-aws-proxy-*\` que traiga el viewer, para que nadie pueda suplantar el
        // origen o el JWE desde fuera; (2) si la ruta exige \`traffic_token\`
        // (\`m.t\` no vacío), lo comprueba en tiempo constante contra la cabecera
        // \`e2b-traffic-access-token\` o la cookie \`rayito_tt\`; (3) llama a
        // \`cf.updateRequestOrigin\` con el endpoint de la ruta y las cabeceras que
        // el proxy de AWS Lambda MicroVMs espera.
        //
        // \`export\` sólo en las funciones puras de abajo (para que
        // \`infra/functions/tests/*.test.mjs\` las importe con Node directamente);
        // \`handler\` se queda sin \`export\`, tal cual el ejemplo oficial de AWS para
        // \`AWS::CloudFront::Function\` (sin verificar aún contra una distribución
        // real: D3/DOM-2 lo confirma en la etapa de aceptación AWS).

        import cf from "cloudfront";
        import crypto from "crypto";

        const kvsHandle = cf.kvs();

        export const JWE_KEY_PREFIX = "j:";
        export const META_KEY_PREFIX = "m:";
        export const TRAFFIC_TOKEN_HEADER = "e2b-traffic-access-token";
        export const TRAFFIC_TOKEN_COOKIE = "rayito_tt";
        export const PROXY_AUTH_HEADER = "x-aws-proxy-auth";
        export const PROXY_PORT_HEADER = "x-aws-proxy-port";
        export const AWS_PROXY_HEADER_PREFIX = "x-aws-proxy-";

        /** "8000-ws-7.sbx.example.com" -> "8000-ws-7": la etiqueta es la primera
         * componente del host, siempre (\`_domain.route_host\`). */
        export function routeLabel(host) {
          const dot = host.indexOf(".");
          return dot === -1 ? host : host.substring(0, dot);
        }

        /** El puerto es el prefijo numérico de la etiqueta, antes del primer guion. */
        export function portFromLabel(label) {
          const dash = label.indexOf("-");
          return dash === -1 ? label : label.substring(0, dash);
        }

        /** Nunca reenvía una cabecera \`x-aws-proxy-*\` que haya puesto el viewer:
         * sólo las que pone esta Function, más abajo, cuentan. */
        export function stripUpstreamProxyHeaders(headers) {
          for (const name in headers) {
            if (Object.prototype.hasOwnProperty.call(headers, name) && name.indexOf(AWS_PROXY_HEADER_PREFIX) === 0) {
              delete headers[name];
            }
          }
        }

        /** La cookie \`name\` del valor crudo de la cabecera \`cookie\`, o \`null\`. */
        export function readCookie(headers, name) {
          const cookieHeader = headers.cookie;
          if (!cookieHeader) {
            return null;
          }
          const entries = Array.isArray(cookieHeader) ? cookieHeader : [cookieHeader];
          for (const entry of entries) {
            const parts = (entry.value || "").split(";");
            for (const part of parts) {
              const eq = part.indexOf("=");
              if (eq === -1) {
                continue;
              }
              if (part.substring(0, eq).trim() === name) {
                return part.substring(eq + 1).trim();
              }
            }
          }
          return null;
        }

        /** sha256 hexadecimal de \`value\` (mismo formato que \`_domain.traffic_token_digest\`). */
        export function sha256Hex(value) {
          const hash = crypto.createHash("sha256");
          hash.update(value);
          return hash.digest("hex");
        }

        /** Comparación en tiempo constante de dos cadenas hex de igual longitud
         * esperada (sha256 siempre produce 64 caracteres); distinta longitud ya es
         * "no coincide" sin más coste. */
        export function constantTimeEqual(a, b) {
          if (a.length !== b.length) {
            return false;
          }
          let diff = 0;
          for (let i = 0; i < a.length; i += 1) {
            diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
          }
          return diff === 0;
        }

        /** \`true\` si el \`traffic_token\` que trae la petición coincide con el hash
         * guardado en la ruta (\`metadata.t\`); \`metadata.t === ""\` es una ruta
         * pública (sin token que comprobar). */
        export function trafficTokenAccepted(headers, metadataTokenHash) {
          if (!metadataTokenHash) {
            return true;
          }
          const headerValue = headers[TRAFFIC_TOKEN_HEADER] && headers[TRAFFIC_TOKEN_HEADER].value;
          const provided = headerValue || readCookie(headers, TRAFFIC_TOKEN_COOKIE);
          if (!provided) {
            return false;
          }
          return constantTimeEqual(sha256Hex(provided), metadataTokenHash);
        }

        async function handler(event) {
          const request = event.request;
          stripUpstreamProxyHeaders(request.headers);
          const label = routeLabel(request.headers.host.value);
          let jwe;
          let metadata;
          try {
            jwe = await kvsHandle.get(JWE_KEY_PREFIX + label, { format: "string" });
            metadata = await kvsHandle.get(META_KEY_PREFIX + label, { format: "json" });
          } catch (err) {
            return { statusCode: 404, statusDescription: "Not Found", headers: {} };
          }
          if (!trafficTokenAccepted(request.headers, metadata.t)) {
            return { statusCode: 403, statusDescription: "Forbidden", headers: {} };
          }
          cf.updateRequestOrigin({
            domainName: metadata.e,
            customHeaders: {
              [PROXY_AUTH_HEADER]: jwe,
              [PROXY_PORT_HEADER]: portFromLabel(label),
            },
          });
          return request;
        }

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "Rayito custom-domain (\${PublicDomain})"
        HttpVersion: http2
        Aliases:
          - !Sub "*.\${PublicDomain}"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          # Placeholder only: every real request's origin is replaced by
          # RouterFunction via cf.updateRequestOrigin() before it leaves the
          # edge (AWS_API_NOTES.md section 29). This origin is never actually
          # contacted when the Function finds a route; a request for a label
          # with no route gets a 404 straight from the Function instead.
          - Id: PlaceholderOrigin
            DomainName: !Sub "unresolved.invalid.\${AWS::Region}.rayito.example"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: PlaceholderOrigin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          # Dynamic per-sandbox routing can never be cached; forwards
          # everything the AWS Lambda MicroVMs proxy and WebSocket upgrades
          # need (managed policies: CachingDisabled, AllViewer).
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt RouterFunction.FunctionMetadata.FunctionARN

Outputs:
  DistributionId:
    Description: Pass to destroy()/status() if you ever need the raw CloudFront distribution id.
    Value: !Ref Distribution
  DistributionDomainName:
    Description: The *.cloudfront.net name; CNAME/ALIAS your DNS for *.<PublicDomain> to this.
    Value: !GetAtt Distribution.DomainName
  KvsArn:
    Description: Read by CustomDomain.deploy()/.status() to find the KeyValueStore for register()/unregister().
    Value: !GetAtt RouteKeyValueStore.Arn
`;
// Base64 of the component's Lambda source zip, or undefined when it has none.
export const ARTIFACT_BASE64: string | undefined = undefined;
