// GENERATED by scripts/gen_stack_assets.py from infra/custom-domain.yaml.
// Do not edit by hand: run `python scripts/gen_stack_assets.py`.
export const TEMPLATE_BODY = `AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Rayito m15-custom-domain (optional, experimental): a CloudFront distribution
  with a wildcard alias, its viewer-request CloudFront Function (dynamic
  per-request origin selection via cf.updateRequestOrigin, runtime
  cloudfront-js-2.0) and the CloudFront KeyValueStore it reads routes from.
  No Lambda, no VPC, no IAM role beyond what CloudFront itself needs
  (CAPABILITY_NAMED_IAM is NOT required by this template; kept for parity
  with other OptionalStack components only if a future Lambda refresher is
  added). Parameters and actions: AWS_API_NOTES.md section 29. Deploy it only
  if you use domain=/CustomDomain; delete the stack to remove the
  distribution, the Function and the KeyValueStore (no sandbox data is ever
  stored in the KVS, only ephemeral routing entries).

Parameters:
  PublicDomain:
    Type: String
    MinLength: 1
    Description: >-
      Your own domain (D3, maintainer-owned). The distribution's alias is
      *.<PublicDomain>; CustomDomain(public_domain=PublicDomain) computes
      per-sandbox hostnames under it.
  CertificateArn:
    Type: String
    MinLength: 1
    AllowedPattern: "^arn:aws[a-zA-Z-]*:acm:us-east-1:[0-9]{12}:certificate/.+$"
    Description: >-
      ARN of an ACM certificate in us-east-1 covering *.<PublicDomain>
      (CloudFront requires us-east-1 certificates regardless of the
      distribution's own region).

Resources:
  RouteKeyValueStore:
    Type: AWS::CloudFront::KeyValueStore
    Properties:
      Name: !Sub "rayito-custom-domain-\${AWS::StackName}"
      Comment: >-
        Rayito custom-domain routes: j:<port>-<alias> / m:<port>-<alias>.
        See infra/custom-domain.yaml.

  RouterFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "rayito-custom-domain-router-\${AWS::StackName}"
      FunctionConfig:
        Comment: >-
          Rayito custom-domain router: strips any viewer x-aws-proxy-*
          header, checks the route's traffic token (constant-time) and
          calls cf.updateRequestOrigin() with the sandbox's endpoint and
          the proxy headers it expects. Source of truth:
          infra/functions/custom_domain_router.js (kept in sync, minus its
          \`export \` keywords, by scripts/tests/test_custom_domain_function_sync.py).
        Runtime: cloudfront-js-2.0
        KeyValueStoreAssociations:
          - KeyValueStoreARN: !GetAtt RouteKeyValueStore.Arn
      AutoPublish: true
      FunctionCode: |
        // Rayito m15-custom-domain: enrutado dinámico de CloudFront por sandbox.
        //
        // Asociada como evento \`viewer-request\` (único evento donde CloudFront
        // permite \`cf.updateRequestOrigin\`, ver AWS_API_NOTES.md §29). Runtime
        // \`cloudfront-js-2.0\` (exigido por el helper de KVS y por
        // \`cf.updateRequestOrigin\`). El KeyValueStore asociado guarda dos claves
        // por ruta (\`_custom_domain/_domain.py\` del SDK):
        //   j:<puerto>-<alias>  -> el JWE vigente de \`create-microvm-auth-token\`
        //   m:<puerto>-<alias>  -> JSON compacto {"e": endpoint, "t": sha256(token) o "", "x": exp}
        //
        // Pasos (arquitectura M15 §7.8, función pura \`route()\` más abajo): (1)
        // borra cualquier cabecera \`x-aws-proxy-*\` que traiga el viewer, para que
        // nadie pueda suplantar el origen o el JWE desde fuera; (2) rechaza sin
        // tocar el KVS un puerto reservado (RESERVED_PORTS, defensa en
        // profundidad — el SDK ya nunca registra una ruta ahí); (3) trata una ruta
        // cuyo \`m.x\` (expires_at, epoch en segundos) ya pasó como si no existiera
        // — un 404, igual que una ruta nunca registrada, no un 403 — porque
        // \`register(ttl_seconds=)\`/\`refresh()\` sólo escriben ese campo, nadie lo
        // borra solo (hallazgo del review de PR #74: antes \`route()\` nunca lo
        // leía, así que una ruta huérfana sólo dejaba de servir cuando caducaba el
        // JWE en sí, del lado del proxy de AWS, no por el TTL que el SDK dice
        // ofrecer); (4) si la ruta exige \`traffic_token\` (\`m.t\` no vacío), lo
        // comprueba en tiempo constante contra la cabecera
        // \`e2b-traffic-access-token\` o la cookie \`rayito_tt\`; (5) llama a
        // \`cf.updateRequestOrigin\` con el endpoint de la ruta y las cabeceras que
        // el proxy de AWS Lambda MicroVMs espera.
        //
        // \`import cf from "cloudfront"\` es la forma documentada por AWS de acceder
        // a los builtins del runtime \`cloudfront-js-2.0\` (no una importación de
        // paquete), así que se mantiene en el código desplegado. \`export\`, en
        // cambio, no está documentado como soportado por ese runtime para las
        // propias declaraciones de la función — nunca se ha comprobado contra una
        // distribución real — así que \`scripts/tests/test_custom_domain_function_sync.py\`
        // exige que el \`FunctionCode\` embebido en \`infra/custom-domain.yaml\` sea
        // este mismo fichero con cada \`export \` de nivel superior quitado; las
        // declaraciones \`export\` de aquí existen sólo para que
        // \`infra/functions/tests/*.test.mjs\` las importe con Node directamente.
        //
        // \`cloudfront-js-2.0\` no es ES moderno completo: rechaza al compilar
        // \`for...of\` y los parámetros por defecto (medido con \`TestFunction\`, Q121 de
        // AWS_API_NOTES.md), y Node los acepta, así que los tests de Node no lo
        // detectan. Aquí sólo bucles con índice y valores por defecto explícitos.

        import cf from "cloudfront";
        import crypto from "crypto";

        const kvsHandle = cf.kvs();

        const JWE_KEY_PREFIX = "j:";
        const META_KEY_PREFIX = "m:";
        const TRAFFIC_TOKEN_HEADER = "e2b-traffic-access-token";
        const TRAFFIC_TOKEN_COOKIE = "rayito_tt";
        const PROXY_AUTH_HEADER = "x-aws-proxy-auth";
        const PROXY_PORT_HEADER = "x-aws-proxy-port";
        const AWS_PROXY_HEADER_PREFIX = "x-aws-proxy-";

        // \`limits.json\` \`reservedPorts\` (ADR-006: 8080 es \`rayd\`, 9000 los hooks);
        // espejo literal de \`RESERVED_PORTS\` en \`_limits.py\`/\`limits.ts\`, verificado
        // igual contra \`limits.json\` por
        // \`scripts/tests/test_custom_domain_function_sync.py::test_reserved_ports_match_limits_json\`
        // (este runtime no puede importar un módulo generado: CloudFront Functions
        // sólo resuelve los builtins \`cloudfront\`/\`crypto\`, nunca un fichero propio).
        const RESERVED_PORTS = [8080, 9000];

        /** "8000-ws-7.sbx.example.com" -> "8000-ws-7": la etiqueta es la primera
         * componente del host, siempre (\`_domain.route_host\`), en minúsculas (una
         * etiqueta DNS no distingue mayúsculas; el KVS sí). */
        function routeLabel(host) {
          const lower = host.toLowerCase();
          const dot = lower.indexOf(".");
          return dot === -1 ? lower : lower.substring(0, dot);
        }

        /** El puerto es el prefijo numérico de la etiqueta, antes del primer guion. */
        function portFromLabel(label) {
          const dash = label.indexOf("-");
          return dash === -1 ? label : label.substring(0, dash);
        }

        /** Nunca reenvía una cabecera \`x-aws-proxy-*\` que haya puesto el viewer:
         * sólo las que pone esta Function, más abajo, cuentan. */
        function stripUpstreamProxyHeaders(headers) {
          for (const name in headers) {
            if (Object.prototype.hasOwnProperty.call(headers, name) && name.indexOf(AWS_PROXY_HEADER_PREFIX) === 0) {
              delete headers[name];
            }
          }
        }

        /** La cookie \`name\` del objeto \`event.request.cookies\` de CloudFront
         * Functions (\`{nombre: {value}}\`), o \`null\`. CloudFront entrega ahí las
         * cookies ya parseadas; con un evento de \`TestFunction\` que sólo trae
         * \`cookies\`, leer la cabecera \`cookie\` daba 403 (Q121). */
        function readEventCookie(cookies, name) {
          const entry = cookies && cookies[name];
          return entry && entry.value ? entry.value : null;
        }

        /** La cookie \`name\` del valor crudo de la cabecera \`cookie\`, o \`null\`
         * (respaldo de \`readEventCookie\` por si la cabecera llega sin parsear). */
        function readCookie(headers, name) {
          const cookieHeader = headers.cookie;
          if (!cookieHeader) {
            return null;
          }
          const entries = Array.isArray(cookieHeader) ? cookieHeader : [cookieHeader];
          for (let i = 0; i < entries.length; i += 1) {
            const parts = (entries[i].value || "").split(";");
            for (let j = 0; j < parts.length; j += 1) {
              const part = parts[j];
              const eq = part.indexOf("=");
              if (eq === -1) {
                continue;
              }
              if (part.substring(0, eq).trim() === name) {
                return part.substring(eq + 1).trim();
              }
            }
          }
          return null;
        }

        /** sha256 hexadecimal de \`value\` (mismo formato que \`_domain.traffic_token_digest\`). */
        function sha256Hex(value) {
          const hash = crypto.createHash("sha256");
          hash.update(value);
          return hash.digest("hex");
        }

        /** Comparación en tiempo constante de dos cadenas hex de igual longitud
         * esperada (sha256 siempre produce 64 caracteres); distinta longitud ya es
         * "no coincide" sin más coste. */
        function constantTimeEqual(a, b) {
          if (a.length !== b.length) {
            return false;
          }
          let diff = 0;
          for (let i = 0; i < a.length; i += 1) {
            diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
          }
          return diff === 0;
        }

        /** \`true\` si el \`traffic_token\` que trae la petición coincide con el hash
         * guardado en la ruta (\`metadata.t\`); \`metadata.t === ""\` es una ruta
         * pública (sin token que comprobar). \`cookies\` es \`event.request.cookies\`. */
        function trafficTokenAccepted(headers, metadataTokenHash, cookies) {
          if (!metadataTokenHash) {
            return true;
          }
          const headerValue = headers[TRAFFIC_TOKEN_HEADER] && headers[TRAFFIC_TOKEN_HEADER].value;
          const provided =
            headerValue ||
            readEventCookie(cookies, TRAFFIC_TOKEN_COOKIE) ||
            readCookie(headers, TRAFFIC_TOKEN_COOKIE);
          if (!provided) {
            return false;
          }
          return constantTimeEqual(sha256Hex(provided), metadataTokenHash);
        }

        /**
         * La decisión de enrutado, pura: nunca toca \`cf.updateRequestOrigin\` ni la
         * respuesta HTTP final, así que se prueba con una \`kvsGet\` falsa
         * (\`infra/functions/tests/custom_domain_router.test.mjs\`) sin runtime de
         * CloudFront. \`kvsGet(key, format)\` es \`(key, format) =>
         * kvsHandle.get(key, {format})\` en producción (ver \`handler\` más abajo).
         *
         * @param now Reloj inyectable para los tests (epoch en milisegundos, como
         *   \`Date.now()\`, su valor por defecto); \`metadata.x\` llega en segundos
         *   (\`_domain.RouteMetadata.encode\`).
         * @returns \`{kind: "not-found"}\` (404: puerto reservado, sin ruta en el
         *   KVS, o \`m.x\` ya pasado), \`{kind: "forbidden"}\` (403: \`traffic_token\`
         *   ausente o incorrecto), o \`{kind: "origin", domainName, customHeaders}\`
         *   (pasa a \`cf.updateRequestOrigin\` tal cual).
         */
        async function route(request, kvsGet, now) {
          // Sin parámetro por defecto (\`now = Date.now\`): \`cloudfront-js-2.0\` lo
          // rechaza al compilar (\`SyntaxError: Unexpected token "="\`, Q121).
          const clock = now || Date.now;
          stripUpstreamProxyHeaders(request.headers);
          const label = routeLabel(request.headers.host.value);
          const port = portFromLabel(label);
          // Defensa en profundidad: el SDK nunca registra una ruta en un puerto
          // reservado (\`_domain.validate_route_port\`), pero si alguna vez hubiera
          // una entrada residual, no responder huecos a un host fabricado a mano
          // ahorra además la consulta al KVS.
          if (RESERVED_PORTS.includes(Number(port))) {
            return { kind: "not-found" };
          }
          let jwe;
          let metadata;
          try {
            jwe = await kvsGet(JWE_KEY_PREFIX + label, "string");
            metadata = await kvsGet(META_KEY_PREFIX + label, "json");
          } catch (err) {
            return { kind: "not-found" };
          }
          // \`m.x\` es el único campo que \`register()\`/\`refresh()\` escriben para
          // acotar una ruta huérfana (T25); tratarla como "no encontrada", no
          // "prohibida", porque desde fuera una ruta caducada no debe distinguirse
          // de una que nunca existió.
          if (typeof metadata.x === "number" && clock() >= metadata.x * 1000) {
            return { kind: "not-found" };
          }
          if (!trafficTokenAccepted(request.headers, metadata.t, request.cookies)) {
            return { kind: "forbidden" };
          }
          return {
            kind: "origin",
            domainName: metadata.e,
            customHeaders: {
              [PROXY_AUTH_HEADER]: jwe,
              [PROXY_PORT_HEADER]: port,
            },
          };
        }

        async function handler(event) {
          const decision = await route(event.request, (key, format) => kvsHandle.get(key, { format }));
          if (decision.kind === "not-found") {
            return { statusCode: 404, statusDescription: "Not Found", headers: {} };
          }
          if (decision.kind === "forbidden") {
            return { statusCode: 403, statusDescription: "Forbidden", headers: {} };
          }
          cf.updateRequestOrigin({ domainName: decision.domainName, customHeaders: decision.customHeaders });
          return event.request;
        }
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "Rayito custom-domain (\${PublicDomain})"
        HttpVersion: http2
        Aliases:
          - !Sub "*.\${PublicDomain}"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          # Placeholder only: every real request's origin is replaced by
          # RouterFunction via cf.updateRequestOrigin() before it leaves the
          # edge (AWS_API_NOTES.md section 29). This origin is never actually
          # contacted when the Function finds a route; a request for a label
          # with no route gets a 404 straight from the Function instead.
          - Id: PlaceholderOrigin
            DomainName: !Sub "unresolved.invalid.\${AWS::Region}.rayito.example"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: PlaceholderOrigin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          # Dynamic per-sandbox routing can never be cached; forwards
          # everything the AWS Lambda MicroVMs proxy and WebSocket upgrades
          # need except the viewer's own Host header (managed policies:
          # CachingDisabled, AllViewerExceptHostHeader). Forwarding Host
          # would send the viewer's \`<port>-<alias>.<PublicDomain>\` to
          # whatever origin RouterFunction picks via updateRequestOrigin,
          # and CloudFront validates that origin's TLS certificate (and
          # sends it as SNI) against the forwarded Host — the Lambda
          # MicroVMs endpoint's own certificate never matches the
          # customer's domain, so every request would 502 (DOM-2,
          # AWS_API_NOTES.md §29).
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt RouterFunction.FunctionMetadata.FunctionARN

Outputs:
  DistributionId:
    Description: Pass to destroy()/status() if you ever need the raw CloudFront distribution id.
    Value: !Ref Distribution
  DistributionDomainName:
    Description: The *.cloudfront.net name; CNAME/ALIAS your DNS for *.<PublicDomain> to this.
    Value: !GetAtt Distribution.DomainName
  KvsArn:
    Description: Read by CustomDomain.deploy()/.status() to find the KeyValueStore for register()/unregister().
    Value: !GetAtt RouteKeyValueStore.Arn
`;
// Base64 of the component's Lambda source zip, or undefined when it has none.
export const ARTIFACT_BASE64: string | undefined = undefined;
