// GENERATED by scripts/gen_stack_assets.py from infra/efs-volumes.yaml.
// Do not edit by hand: run `python scripts/gen_stack_assets.py`.
export const TEMPLATE_BODY = `AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Rayito M15 efs-volumes (ADR-018, experimental): an encrypted, Elastic
  Throughput EFS file system reachable only from a Lambda Network Connector
  dedicated to it, plus the mount-target security group, the file-system
  policy (TLS + access point + mount-target only, no anonymous NFS client)
  and the connector's operator role. Nothing here mounts anything inside a
  sandbox: rayd's only adapter today is UnavailableEfsMounter, ahead of the
  EFS-1..EFS-20 measurement campaign
  (docs/research/2026-10-efs-persistence.md). Pass the ConnectorArn output as
  Sandbox.create(egress=[...]) and the FileSystemId to VolumeStore(...).
  Property names come from the CloudFormation resource reference for
  AWS::EFS::FileSystem, AWS::EFS::MountTarget and
  AWS::Lambda::NetworkConnector; see infra/README.md and AWS_API_NOTES.md
  section 22. RetainData=true (the default) keeps the file system and its
  data on stack deletion; set it to false to let destroy() remove them too.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC of the subnets below; both security groups are created here.
  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      First subnet (its own AZ) for a mount target and for the connector's
      ENIs. EFS allows at most one mount target per AZ.
  SubnetId2:
    Type: String
    Default: ""
    Description: Second subnet's id (different AZ from SubnetId1); empty = none.
  SubnetId3:
    Type: String
    Default: ""
    Description: Third subnet's id (different AZ); empty = none.
  ConnectorName:
    Type: String
    Default: rayito-efs
    AllowedPattern: "^[a-zA-Z0-9_-]{1,64}$"
    Description: Unique name of the connector within the account and Region.
  RetainData:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: >-
      "true" (default): deleting this stack keeps the file system and its
      data. "false": destroy() deletes them too, with everything they hold.

Conditions:
  HasSubnet2: !Not [!Equals [!Ref SubnetId2, ""]]
  HasSubnet3: !Not [!Equals [!Ref SubnetId3, ""]]
  RetainFileSystem: !Equals [!Ref RetainData, "true"]

Resources:
  # Egress from the connector's ENIs: only NFS (2049) to the mount-target
  # security group, mirroring infra/egress-connector.yaml's localhost
  # placeholder rule (EC2's implicit allow-all egress rule only disappears
  # once at least one explicit rule exists).
  ConnectorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Rayito EFS connector egress for \${ConnectorName}
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 127.0.0.1/32
          Description: placeholder that removes the implicit allow-all egress rule
      Tags:
        - Key: rayito
          Value: efs-volumes-connector

  # Ingress on the mount targets: only NFS (2049), only from the connector's
  # own security group (never a CIDR: this is the one guest allowed to speak
  # NFS to this file system, research doc section 4.6).
  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Rayito EFS mount targets for \${ConnectorName}
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !Ref ConnectorSecurityGroup
          Description: NFS from the Rayito EFS connector only
      Tags:
        - Key: rayito
          Value: efs-volumes-mount-target

  FileSystem:
    Type: AWS::EFS::FileSystem
    DeletionPolicy: !If [RetainFileSystem, Retain, Delete]
    UpdateReplacePolicy: !If [RetainFileSystem, Retain, Delete]
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      ThroughputMode: elastic
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      FileSystemTags:
        - Key: rayito
          Value: efs-volumes
      # Three denies (research doc section 4.6): no plaintext NFS, no
      # anonymous client without an access point, and only a request that
      # actually came in through a mount target (never a VPC endpoint or a
      # cross-account path). \`elasticfilesystem:AccessPointArn\` being null
      # is exactly "no access point named".
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyNonTls
            Effect: Deny
            Principal: "*"
            Action: "elasticfilesystem:*"
            Resource: "*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
          - Sid: DenyWithoutAccessPoint
            Effect: Deny
            Principal: "*"
            Action:
              - elasticfilesystem:ClientMount
              - elasticfilesystem:ClientWrite
            Resource: "*"
            Condition:
              "Null":
                elasticfilesystem:AccessPointArn: "true"
          - Sid: DenyWithoutMountTarget
            Effect: Deny
            Principal: "*"
            Action:
              - elasticfilesystem:ClientMount
              - elasticfilesystem:ClientWrite
            Resource: "*"
            Condition:
              Bool:
                elasticfilesystem:AccessedViaMountTarget: "false"

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetId1
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Condition: HasSubnet2
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetId2
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTarget3:
    Type: AWS::EFS::MountTarget
    Condition: HasSubnet3
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetId3
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  # Lambda assumes this role to create, describe and delete the connector's
  # ENIs; same shape as infra/egress-connector.yaml's OperatorRole.
  OperatorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
      Policies:
        - PolicyName: manage-connector-enis
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcs
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                Resource: "*"

  Connector:
    Type: AWS::Lambda::NetworkConnector
    Properties:
      Name: !Ref ConnectorName
      OperatorRole: !GetAtt OperatorRole.Arn
      Configuration:
        VpcEgressConfiguration:
          AssociatedComputeResourceTypes:
            - MicroVm
          NetworkProtocol: IPv4
          SecurityGroupIds:
            - !Ref ConnectorSecurityGroup
          SubnetIds:
            - !Ref SubnetId1
            - !If [HasSubnet2, !Ref SubnetId2, !Ref AWS::NoValue]
            - !If [HasSubnet3, !Ref SubnetId3, !Ref AWS::NoValue]

Outputs:
  FileSystemId:
    Description: Pass it as VolumeStore(file_system_id=...).
    Value: !Ref FileSystem
  FileSystemArn:
    Value: !GetAtt FileSystem.Arn
  ConnectorArn:
    Description: Pass it as Sandbox.create(egress=[ConnectorArn]).
    Value: !GetAtt Connector.Arn
  ConnectorState:
    Value: !GetAtt Connector.State
  MountTargetSecurityGroupId:
    Value: !Ref MountTargetSecurityGroup
  CallerPolicyStatement:
    Description: >-
      The statement the SDK caller needs on top of infra/iam.yaml's execution
      role (elasticfilesystem:ClientMount/ClientWrite on the file system,
      conditioned on an access point ARN) to pass this connector.
    Value: !Sub '{"Effect":"Allow","Action":"lambda:PassNetworkConnector","Resource":"\${Connector.Arn}"}'
`;
// Base64 of the component's Lambda source zip, or undefined when it has none.
export const ARTIFACT_BASE64: string | undefined = undefined;
