// GENERATED by scripts/gen_stack_assets.py from infra/metadata-index.yaml.
// Do not edit by hand: run `python scripts/gen_stack_assets.py`.
export const TEMPLATE_BODY = `AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Rayito M14 (optional): the DynamoDB table of the metadata index
  (DynamoDbIndex / index=) plus two least-privilege IAM managed policies for
  the SDK caller. On-demand billing and TTL on expires_at: an empty table
  costs $0 and expired rows are deleted for free. Action names and parameters:
  AWS_API_NOTES.md section 20. Deploy it only if you use the index; delete the
  stack to remove the table and the policies.

Parameters:
  TableName:
    Type: String
    Default: rayito-sandboxes
    MinLength: 3
    MaxLength: 255
    AllowedPattern: "^[A-Za-z0-9_.-]+$"
    Description: >-
      Name of the index table (DynamoDbIndex("rayito-sandboxes") /
      new DynamoDbIndex({ tableName }) / rayito sandbox list --index-table).
  PointInTimeRecovery:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: >-
      Continuous backups (billed per GB-month). Off by default: the rows are an
      immutable copy of non-secret metadata that expires with the sandbox.
  DeletionProtection:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Blocks DeleteTable (and stack deletion) while "true".

Resources:
  MetadataIndexTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref PointInTimeRecovery
      DeletionProtectionEnabled: !Ref DeletionProtection

  RayitoIndexWriter:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: >-
        Rayito metadata index writer: Sandbox.create(index=) and
        PoolConfig(index=) put one row per sandbox (PutItem, conditional).
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PutIndexRows
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt MetadataIndexTable.Arn

  RayitoIndexReader:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: >-
        Rayito metadata index reader: Sandbox.list(metadata=, index=) and
        paginate() read candidate rows (BatchGetItem).
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ReadIndexRows
            Effect: Allow
            Action:
              - dynamodb:BatchGetItem
            Resource: !GetAtt MetadataIndexTable.Arn

Outputs:
  TableName:
    Description: Pass it to DynamoDbIndex(...) / --index-table.
    Value: !Ref MetadataIndexTable
  TableArn:
    Value: !GetAtt MetadataIndexTable.Arn
  WriterPolicyArn:
    Description: Attach to the identity that creates sandboxes or runs a pool.
    Value: !Ref RayitoIndexWriter
  ReaderPolicyArn:
    Description: Attach to the identity that lists sandboxes with the index.
    Value: !Ref RayitoIndexReader
`;
// Base64 of the component's Lambda source zip, or undefined when it has none.
export const ARTIFACT_BASE64: string | undefined = undefined;
